### ISSUE TITLE
[BUG] Error "Attempt to write to field" when pushing new entry to gitlab repository

### ISSUE THREAD

**Issue by pescepalla** [zeapo/Android-Password-Store#2068] opened 2022-08-21 09:52 UTC
### Describe the bug

Pushing results in error message: "Attempt to write to field 'org.eclipse.jgit.internal.storage.pack.ObjectToPack org.eclipse.git.internal.storage.pack.DeltaWindowEntry.object' on a null object reference"

### Steps to reproduce

1. Link to external gitlab repo through SSH
2. Create a new entry
3. Push to repository

### Expected behavior

Pushing should be successful without error messages

### Screenshots

![Screenshot_20220821-114407_Password Store](https://user-images.githubusercontent.com/46329185/185785557-b6358c5e-9d85-43d0-b908-d9e1be587e56.png)

### Device information

- Device: Fairphone 4
- OS: Android 12
- App version: 1.13.5

**Comment by msfjarvis** [comment] 2022-08-21 09:55
Duplicate of #1581 and #1623, this is a device-specific problem that was [unknowingly fixed](https://github.com/android-password-store/Android-Password-Store/issues/1581#issuecomment-1001230060) in our development branch.

**Comment by pescepalla** [comment] 2022-08-21 09:55
Perfect thank you. Will wait for the update.

**Closed as not planned by msfjarvis** 2022-08-21 09:55 UTC
Labels: C-bug, S-wontfix
