### ISSUE TITLE
[BUG] An error occures during a git push

### ISSUE THREAD

**Issue by doronbehar** [zeapo/Android-Password-Store#2794] opened 2023-12-03 07:23 UTC
### Describe the bug

I get this error message when I try to `git push`:

![Attempt to write to field 'org.eclipse.jgit.internal.storage.pack.ObjectToPack org.eclipse.jgit.internal.storage.pack.DeltaWindowEntry.object' on a null object reference](https://github.com/android-password-store/Android-Password-Store/assets/10998835/49606efc-29aa-45dc-9e7f-7da22e641287)

In the past I managed to `git push` successfully - not sure what happened since. The app hasn't been updated for two years.

### Steps to reproduce

`git push`

### Expected behavior

No error

### Device information

- Device: Google Pixel 3a
- OS: GrapheneOS
- App version: 1.13.5

### Additional context

Could it be this issue was fixed since the last release? I see this repository is somewhat active - it'd be nice to get a release with bug fixes...

**Comment by msfjarvis** [comment] 2023-12-03 08:40
Dupe of #2068, #1641, #1623, and #1581, this is a GrapheneOS problem that is [apparently fixed](https://github.com/android-password-store/Android-Password-Store/issues/1581#issuecomment-1001230060) in our development branch. Check [the docs](https://docs.passwordstore.app/docs/users/release-channels) for how to obtain a snapshot release for the same.

**Closed as not planned by msfjarvis** 2023-12-03 08:40 UTC
Labels: C-bug, S-duplicate
