### ISSUE TITLE
Add possibility to sign commit with gpg key

### ISSUE THREAD

**Issue by meaz** [zeapo/Android-Password-Store#2214] opened 2022-10-26 15:35 UTC
Hi,

at the moment, you can set up a name and a username in the local git settings of Password Store. It would be nice to be able to add the "signing key" option from git so that all commits would be signed with the gpg key.

**Comment by msfjarvis** [comment] 2022-10-26 16:43
Duplicate of #1670 and #1249.

**Closed as not planned by msfjarvis** 2022-10-26 16:43 UTC
Labels: S-invalid
