### ISSUE TITLE
Autofill non-inline presentation does not work on API 30 and above

### ISSUE THREAD

**Issue by plant7403** [zeapo/Android-Password-Store#1434] opened 2021-06-07 15:33 UTC
Version: 2.0.0-SNAPSHOT
Describe the bug:
Autofill doesn't work, Leaks constantly drops notifications like: "Found x retained objects grouped as..."
Logcat:
```
┬───
│ GC Root: Global variable in native code
│
├─ android.service.autofill.AutofillService$1 instance
│    Leaking: UNKNOWN
│    Retaining 2.3 kB in 22 objects
│    Anonymous subclass of android.service.autofill.IAutoFillService$Stub
│    this$0 instance of dev.msfjarvis.aps.util.services.OreoAutofillService
│    ↓ AutofillService$1.this$0
│                        ~~~~~~
╰→ dev.msfjarvis.aps.util.services.OreoAutofillService instance
​     Leaking: YES (ObjectWatcher was watching this because dev.msfjarvis.aps.
​     util.services.OreoAutofillService received Service#onDestroy() callback
​     and Service not held by ActivityThread)
​     Retaining 1.8 kB in 21 objects
​     key = 4283a638-c9f8-4388-9e01-d37074733d47
​     watchDurationMillis = 40634
​     retainedDurationMillis = 35631
​     mApplication instance of dev.msfjarvis.aps.Application
​     mBase instance of android.app.ContextImpl

METADATA

Build.VERSION.SDK_INT: 30
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.7
App process name: dev.msfjarvis.aps
Stats: LruCache[maxSize=3000,hits=4713,misses=108969,hitRate=4%]
RandomAccess[bytes=5913891,reads=108969,travel=77851125674,range=37741464,size=4
7171040]
Heap dump reason: 19 retained objects, app is not visible
Analysis duration: 3983 ms 
```

**Comment by msfjarvis** [comment] 2021-06-07 15:49
You can go into the Leaks app and turn off heap dumps from the settings page, though I need to do something about this long-term.

Does Autofill not work at all for you even after disabling heap dumps? What about long pressing on text fields and using the Autofill option there?

**Comment by plant7403** [comment] 2021-06-07 16:07
i can't find the settings there, just about menu
and there's some automatic heap option
even after disabling this it still shows the notifications

on some websites/browsers it's showing autofill button on a long press, on some websites/browsers not
but in any case password store doesn't appear 
(yes, permissions are all allow 😄)

**Comment by plant7403** [comment] 2021-06-09 13:19
UPDATE:
Autofil works, BUT not as popup!!!
I used some FOSS keyboard before, and it accidentally switched to Gboard, and it shows there! 😲 like tabs right in Gboard!

**Comment by fmeum** [comment] 2021-06-14 12:16
@xxxcrow Which keyboard did you use that didn't show autofill suggestions?

**Comment by msfjarvis** [comment] 2021-06-14 12:17
Finally got time to look into this, and we've definitely had a regression where with keyboards that do not support inline presentation, we don't show the pop-up. This applies at least to Android 12 for me and Android 11 for OP. Commenting out the `setInlinePresentation` call makes the pop-up show correctly on Gboard so I'm confused.

> @xxxcrow Which keyboard did you use that didn't show autofill suggestions?

I'm currently trying out [FlorisBoard](https://github.com/florisboard/florisboard) where this is consistently failing.

**Comment by msfjarvis** [comment] 2021-06-14 12:38
With FlorisBoard as the current IME our Autofill matcher doesn't even kick in, which it consistently does with Gboard as the input method. Observed this behavior with `setInlinePresentation` disabled.

**Comment by plant7403** [comment] 2021-06-14 14:42
@msfjarvis I used florisboard, exactly 😃
Also, ok if it fails, it fails for bitwarden too
But for this case bitwarden has accessibility support to show it on the screen 😃 (I'm not sure exactly how it works with bitwarden, but it seems through the accessibility)

**Comment by plant7403** [comment] 2021-07-01 13:04
@msfjarvis did something change in the last snapshots? 
I flashed my phone with new firmware and updated snapshot
Now I have on screen tabs as it was with v1.*

**Comment by msfjarvis** [comment] 2021-07-01 18:26
> @msfjarvis did something change in the last snapshots? 
> I flashed my phone with new firmware and updated snapshot
> Now I have on screen tabs as it was with v1.*

Not really, no. We haven't done any work towards this issue.

**Comment by msfjarvis** [comment] 2021-11-20 08:56
This works for me on Android 11 and 12 now so I'm closing the issue.

**Closed as completed by msfjarvis** 2021-11-20 08:56 UTC
Labels: E-medium, P-high, A-autofill, C-regression, A-UI-UX
