### ISSUE TITLE
[BUG] Corrupts symbolic links, does not display linked passwords

### ISSUE THREAD

**Issue by dlastov** [zeapo/Android-Password-Store#2594] opened 2023-07-08 07:41 UTC
### Describe the bug

Android-Password-Store is not compatible with symbolic links in the password repository:
- It can't read the linked passwords.
- It corrupts the repository by changing the type of the link to an ordinary file and committing that back to the repository.

### Steps to reproduce

1. On a Linux client create a link to password:

```
    # alternative 1: using pass-ln extension (https://github.com/radian-software/pass-ln)
    pass ln myPassword linkToPassword
    pass git push

    # alternative 2:  directly with ln -s and git
    cd $PWD
    ln -s myPassword.gpg linkToPassword.gpg
    git add linkToPassword.gpg
    git commit -m ""
    git push

    #verify that the linkToPassword can be displayed on the Linux client
    pass show linkToPassword
```

2. On the Android-Password-Store:
- update the repository, try to display the linkToPassword: the password can't be displayed
- run "Synchronize repository", try to display the linkToPassword on the Linux client: `pass git pull ; pass show linkToPassword `- does not work anymore

### Expected behavior

The application should display passwords referred to by symbolic links.
Under no circumstances the application should corrupt the links in the repository, even if symbolic links are not supported.

### Device information

- Device: Nokia XR 20
- OS: Android 13
- App version: 1.13.5

**Comment by msfjarvis** [comment] 2023-07-08 08:06
Duplicate of #636

**Closed as not planned by msfjarvis** 2023-07-08 08:06 UTC
Labels: C-bug, S-duplicate

**Comment by Villemoes** [comment] 2023-11-26 19:44
Sure, it's a duplicate of #636, but is there really not anything more that can be done? I see there has been quite a lot of activity, but most of it seems to have been reverted again. For example there's `7a7e58f6 - Revert "Reland symlink support (#1020)"`. But Android 7 was EOL 7 years ago, is maintaining compatibility with that really needed? 

If this just meant that a few passwords were not accessible via the app, that would be fine. But since this manifests by the upstream repo getting broken whenever one syncs back something created on the phone, that's really annoying.

**Comment by msfjarvis** [comment] 2023-11-26 20:27
The problem isn't maintaining compatibility with Android 7 (we only support a minimum of Android 8.1 now), but the fact that the fix does not reside in the app directly. The corruption occurs deep in [JGit](https://www.eclipse.org/jgit/documentation/) and our attempts to plumb in a fix from outside didn't work even on newer versions of Android. Upgrading JGit from the [8 year old version we're on](https://projects.eclipse.org/projects/technology.jgit/releases/3.7.1) to one high enough to properly support symlinks without breaking the app altogether is a large undertaking that I simply do not have the time or motivation for.

**Comment by msfjarvis** [comment] 2023-11-27 12:14
Well that's 3 hours I am not getting back but I've upgraded JGit as far as possible while supporting Android 8.1 and on first glance it seems to support symlinks properly enough with the caveat that the repo needs to be deleted and re-cloned for JGit to do auto discovery for symlink support.

**Comment by Villemoes** [comment] 2023-11-27 13:39
Thanks for taking the time to look at this again. Is there some way I can help testing?

**Comment by msfjarvis** [comment] 2023-11-27 13:47
> Thanks for taking the time to look at this again. Is there some way I can help testing?

You can try the snapshot builds from here: https://docs.passwordstore.app/docs/users/release-channels/

If you're currently using the Play Store version this will install alongside it.

**Comment by Villemoes** [comment] 2023-11-28 20:34
I installed the version built from 2b93b49 on an Android 13 phone, and the symlink stuff seems to work as expected: The app can show passwords whether in a real or symlinked file, creating new passwords in the app and pushing the result to the remote doesn't corrupt the remote.

Do I understand correctly that the app no longer depends on OpenKeychain for the pgp logic? I tried enabling  passphrase caching, but that didn't seem to work; I was prompted every time, even if the app hadn't been closed.

**Comment by msfjarvis** [comment] 2023-11-29 01:06
> I installed the version built from [2b93b49](https://github.com/android-password-store/Android-Password-Store/commit/2b93b49dbe8345cc34b634c48e5967a81aa23e7e) on an Android 13 phone, and the symlink stuff seems to work as expected: The app can show passwords whether in a real or symlinked file, creating new passwords in the app and pushing the result to the remote doesn't corrupt the remote.

Awesome.

> Do I understand correctly that the app no longer depends on OpenKeychain for the pgp logic? I tried enabling passphrase caching, but that didn't seem to work; I was prompted every time, even if the app hadn't been closed.

Correct, OpenKeychain is no longer supported. Passphrase caching should only prompt you for your biometrics or device credentials since it puts the passphrase in an encrypted key-value, if you're being prompted for your key passphrase please file a separate issue.
