### ISSUE TITLE
[BUG] Password Store unavailable on Google Play

### ISSUE THREAD

**Issue by swoh816** [zeapo/Android-Password-Store#2669] opened 2023-09-02 03:45 UTC
### Describe the bug

Password Store is unavailable for most of my devices. I wonder if the app needs update for newer Android OSes (or new devices?)
The only device available for installation via Google Playstore is the device manufactured before 2020. All devices manufactured after 2020 cannot install Password Store via Google Playstore.

Thanks for the amazing work! I really want to use it on my Android..

### Steps to reproduce

1. Go to Play Store on any Android device (in my case, the devices are manufactured after 2022)
2. Search for Password Store
3. The text "This app is available for some of your devices" is displayed, and Password Store is unable to be installed on any of my devices manufactured after 2022.

### Expected behavior

Able to install Password Store on my Android device.

### Screenshots

![image](https://github.com/android-password-store/Android-Password-Store/assets/14903586/2a97887f-86cd-4475-a8c4-38651b0b8ad5)

### Device information

- Device: Galaxy S23 Ultra
- OS: Android 13
- App version: 1.13.5

**Comment by msfjarvis** [comment] 2023-09-02 05:31
Duplicate of #2663, https://github.com/android-password-store/Android-Password-Store/issues/2644, https://github.com/android-password-store/Android-Password-Store/issues/2587, https://github.com/android-password-store/Android-Password-Store/issues/2553, https://github.com/android-password-store/Android-Password-Store/issues/2533 and https://github.com/android-password-store/Android-Password-Store/issues/2417.

**Closed as not planned** 2023-09-02 05:32 UTC
Labels: S-duplicate

**Comment by swoh816** [comment] 2023-09-02 12:53
Thanks! I don't know much about Android nor app dev so I didn't know what keywords to search with regard to this issue
