### ISSUE TITLE
Blank screen displayed on pressing "back" from home screen

### ISSUE THREAD

**Issue by GreenHex** [zeapo/Android-Password-Store#197] opened 2016-07-19 08:32 UTC
This is a bug in latest version 1.2.0.47 (4 July 2016) on my Meizu M2 running Android 5.1.

A blank screen (shown below) is displayed on pressing back button from the app home screen. The previous screen is a password db list (as expected). The list is (correctly) displayed on launch, and this problem occurs only while exiting the application by pressing the back button.

![image](https://cloud.githubusercontent.com/assets/970384/16943482/8dcc1f60-4db9-11e6-8019-a3f011570c5e.png)

**Comment by wongma7** [comment] 2016-07-20 00:31
dupe of https://github.com/zeapo/Android-Password-Store/issues/196 I think. Don't upgrade to 1.2.0.48 though, wait for 1.2.0.49

**Closed** 2016-07-21 12:03 UTC

**Comment by GreenHex** [comment] 2016-10-13 13:45
Please release fixed version 1.2.0.49 in Android app store.
