### ISSUE TITLE
[FEATURE] Automatic synchronisation of password-store repository

### ISSUE THREAD

**Issue by MrPixelized** [zeapo/Android-Password-Store#1133] opened 2020-10-03 17:22 UTC
### Problem statement
It can sometimes be mildly frustrating to have to remember to manually
synchronise passwords with a git server when you open the app, especially
because often times, the first thing you do when you want to retrieve a password
from the password store is synchronise the database manually.

### Proposed solutions
I'd like an optional feature which automatically syncrhonises the password store
every time you open the application (in the case of biometric authorisation,
post-auth). This feature would be enabled and disabled via a binary switch on
the settings screen.

### Alternative solutions
Other solutions to this issue I have considered, which might solve more problems
but come at a cost as well, are:
	- A feature which synchronises the database on a timer.
	- A feature which synchronises the database whenever the phone is unlocked.

### Context
For me personally this isn't a huge issue, though I had thought about it.
What motivated me to create this issue is the fact that other users of `pass`
expressed their mild frustration.

**Comment by msfjarvis** [comment] 2020-10-03 17:36
Duplicate of #277

**Closed as completed by msfjarvis** 2020-10-03 17:36 UTC
