### ISSUE TITLE
[FEATURE] Implement git commit signing

### ISSUE THREAD

**Issue by zneix** [zeapo/Android-Password-Store#1670] opened 2022-01-18 03:11 UTC
### Is your feature request related to a problem? Please describe.

I always sign my commits on desktop and I've found out there's no way to do that with APS. I would really like to keep consistency and security by signing all my git commits with the GPG (similar reasoning as in https://github.com/android-password-store/Android-Password-Store/issues/272#issuecomment-345226028).
While browsing issues on this repository I've discovered that his has been already suggested and talked over in #1249 #272 #170, so technically my request is a duplicate, however some time has passed since closure of #1249 and I think that https://bugs.eclipse.org/bugs/show_bug.cgi?id=547751 implements GPG commit signing.

### Describe the solution you'd like

Implementing mechanism handling git commit signing and adding an option in `Settings > Repository > Git configuration` to autosign all commits that are made within the application and maybe allowing user to specify with which key they want to sign their commits if the key is different than the one used by pass.

### Describe alternatives you've considered

N/A

### Additional context

I noticed that used jgit version is quite old: https://github.com/android-password-store/Android-Password-Store/blob/3ead6596ba9c2b65434f6cd948bf6ebf41a230eb/gradle/libs.versions.toml#L79
There's a lot of newer versions (see https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit) and I wonder if there's anything stopping you from upgrading the dependency - because it looks like commit signing is available only since somewhere around version 5.11.x

**Comment by msfjarvis** [comment] 2022-01-18 05:31
We can't use newer JGit versions because they require newer Java runtimes which are not available on Android. Duplicate of https://github.com/android-password-store/Android-Password-Store/issues/1249

**Closed as completed by msfjarvis** 2022-01-18 05:31 UTC
Labels: C-feature, S-wontfix
