### ISSUE TITLE
[FEATURE] keybase git repo support

### ISSUE THREAD

**Issue by madzohan** [zeapo/Android-Password-Store#3226] opened 2024-09-20 09:44 UTC
### Is your feature request related to a problem? Please describe.

Is there a way to support [**keybase**](https://keybase.io/) git urls?

Now in "Repository information" when I setting "Server" -> "Repository URL" to "keybase://private/blabla/passwords" the app says "The provided repository URL is not valid"

### Describe the solution you'd like

**Android-Password-Store** app is able to clone/pull/push **keybase** git repository.

[Cite from keybase docs](https://book.keybase.io/git):

> Under the hood, Git supports [remote helpers](https://git-scm.com/docs/gitremote-helpers). This allows Git itself to interface with datastores other than the local filesystem. Keybase has created an [open source remote helper](https://github.com/keybase/client/tree/master/go/kbfs/kbfsgit/) that facilitates this interaction, keeping the data in your repository within your control via your local Keybase app.

(if it is possible to use it in this case)

**OR**

[mb integrated **termux** fork like mentioned here ...](https://www.reddit.com/r/termux/comments/13bvnqd/comment/jjcqlny)

### Describe alternatives you've considered

AFAIK there is no android GUI app which can do that (if I'm wrong let me know plz 🙏 ). Only possible way is using **termux** with console {keybase + git + gnupg + pass} apps installed.
On desktop I'm using [qtPass](https://qtpass.org/) (it works with gpg & git & keybase cloned repo) +  [browserpass chrome extension](https://github.com/browserpass/browserpass-extension)

**Comment by msfjarvis** [comment] 2024-09-20 12:15
Duplicate of #1413 and #344

**Closed as not planned** 2024-09-20 12:16 UTC
Labels: C-feature, S-duplicate

**Comment by madzohan** [comment] 2024-10-13 15:56
💩
