### ISSUE TITLE
[BUG] Symbolic links gets removed to have a file that contains the target file name

### ISSUE THREAD

**Issue by etu** [zeapo/Android-Password-Store#1013] opened 2020-08-13 06:13 UTC
**Describe the bug**
If you have a password store repository that contains symbolic links. For instance I want the same information to be available under more than one file/name to match websites that does use the same credentials for whatever reason.

So what this does is that it takes the content of the "file" which is a symbolic link (the content really is the target file name) and makes a new file in place with the same content which isn't a symbolic link. So then the symbolic link doesn't work. And it also pushes this to the git repository.

With the older app this was fine, but I just "upgraded" to this newer app when I found it yesterday :-) It's overall a great update btw, except this behavior.

**To Reproduce**
1. Have a password store repository that contains one or more symbolic link
2. Import that password store to the app
3. See the commit pushed to the repository rewriting all the symbolic links to being files that contains the target filename

**Expected behavior**
Not remove and push the removal of symbolic links.

**Device information (please complete the following information):**
 - Device: OnePlus Nord
 - OS: Oxygen OS 10.5.4.AC01BA, Android version 10
 - App version: 1.10.3

**Additional context**

**Comment by msfjarvis** [comment] 2020-08-13 06:45
This is a duplicate of #636, differently worded but is the same problem.

**Closed as completed by msfjarvis** 2020-08-13 06:45 UTC
