### ISSUE TITLE
[BUG] IPv6 urls using square bracket notation does not connect

### ISSUE THREAD

**Issue by aplund** [zeapo/Android-Password-Store#1120] opened 2020-09-25 23:30 UTC
Set the git server to ssh://username@[fe80::dead:beef]:2323/path/to/repo (substituting real values of course).  I get an EINVAL message when trying to sync the repo.

**Comment by msfjarvis** [comment] 2020-09-29 15:02
I can't reproduce this on my own servers, do you have a screenshot of the error?

**Comment by msfjarvis** [comment] 2020-10-05 13:04
@aplund are you still affected by this issue?

**Comment by aplund** [comment] 2020-10-06 02:03
On v1.12.0 I still have the problem.

I have uploaded a screenshot.

![Screenshot_20201006-114748](https://user-images.githubusercontent.com/1369436/95150376-62117980-07cb-11eb-8ae6-fa1cee72a768.jpg)

The sshd daemon on this host is working and the host responds to pings from other apps.  Perhaps I'm missing a scope component?  The other programs don't seem to need it though.

**Comment by aplund** [comment] 2020-10-06 02:07
Sorry, I forgot to mention that putting in a scope component gives the error: "The provided repository URL is not valid".

**Comment by msfjarvis** [comment] 2020-10-06 06:24
The URL format you need is `ssh://username@[ip::address]:port/full/path/to/repository`, like this: `ssh://msfjarvis@[fe:80:dead:beaf::1]:22/home/msfjarvis/pass-test`.

**Comment by aplund** [comment] 2020-10-06 11:01
> The URL format you need is `ssh://username@[ip::address]:port/full/path/to/repository`, like this: `ssh://msfjarvis@[fe:80:dead:beaf::1]:22/home/msfjarvis/pass-test`.

That is exactly how I have it (except the IPv6 address is an actual fe80:: address as per screenshot).  Syncing the repo gives the EINVAL error above.

**Comment by msfjarvis** [comment] 2020-10-06 11:30
And I still can't reproduce it :/

The closest I can get to that error is when I'm not using a VPN, which results in me not having IPv6 connectivity at all (thanks shit ISPs).

**Comment by aplund** [comment] 2020-10-07 01:52
What happens when you try to explicitly set the zone component?  I get an error saying the format is invalid. Though, I think the OS needs this for some link local address.  On my laptop I get EINVAL without it.

That is try:

ssh://msfjarvis@[fe:80:dead:beaf::1%25eth0]:22/home/msfjarvis/pass-test

where eth0 is replaced by your actual interface name or number.  I get an error saying the username is invalid.

**Comment by ardje** [comment] 2021-10-01 08:48
Guys, if you do link local, the zone is mandatory.
However the formal URI for a link local address has been in flux.
Old version is [ip%interface], new and official version is [ip%25interface].
However ssh itself is not expecting URI, so it needs % and not %25 and it might interpret it as the zone number (you can use interface name or interface number).
A second thing is that for link locals to work, you actually need to indicate that you want any address at getaddrinfo.

@aplund I hope you realise that link local is fe80:: and not fe:80 ... and that it is a typo in your last comment? :-).

Anyway: I think you can get invalid or unresolvable depending on what kind of parsing bug you hit on link local parsing.

But a +1 for supporting link local, because it is one of the most important networks for configuring and maintaining network equipment.

**Comment by msfjarvis** [comment] 2022-04-08 19:26
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).

**Closed as completed by msfjarvis** 2022-04-08 19:26 UTC
Labels: C-bug, E-medium, P-low, S-design, A-auth, S-help-wanted
