### ISSUE TITLE
[BUG] OTP autofill not working

### ISSUE THREAD

**Issue by AustralEpitech** [zeapo/Android-Password-Store#2905] opened 2024-02-15 15:34 UTC
### Describe the bug

I can't get the autofill working for OTP field (the field only appears after filling username / password and clicking login)

Tested on <https://discord.com/login>, <https://github.com/login> and <https://www.ovh.com/auth>.

### Steps to reproduce

1. Go to any website with OTP
2. Autofill Username / Password
3. Click 'Log In' button

### Expected behavior

The OTP code should be filled in automatically or at least show a button to fill it.

### Device information

- Device: Google Pixel 7a
- OS: GrapheneOS 2024020500 (Android 14)
- App version: 2.0.0-SNAPSHOT 68f5628
- Browser: Mull 122.1.0

### Additional context

I'm not sure if this is because of my configuration or maybe because the field only appears on a different page after clicking the 'log in' button...

**Comment by msfjarvis** [comment] 2024-02-15 15:50
Duplicate of #2316

**Comment by AustralEpitech** [comment] 2024-02-15 15:53
I don't mean SMS OTP code, I mean from otp URL ([pass-otp](https://github.com/tadfisher/pass-otp))  
If anything, it's a duplicate of #2200, but since this issue is closed, I wasn't sure if I should respond to it or create a new one

**Comment by msfjarvis** [comment] 2024-02-15 16:02
Apologies, I misread the issue body.

What browser are you using?

**Comment by AustralEpitech** [comment] 2024-02-15 16:06
Mull 122.1.0, but I have the same problem with Fenix (Fennec F-droid) 122.1.0

**Comment by msfjarvis** [comment] 2024-10-12 15:58
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.

**Closed as not planned by msfjarvis** 2024-10-12 15:58 UTC
Labels: C-bug, P-high, A-autofill, C-regression
