### ISSUE TITLE
Add support for ssh auth with OpenKeyChain

### ISSUE THREAD

**Issue by etam** [zeapo/Android-Password-Store#417] opened 2018-07-11 10:03 UTC
TermBot is a terminal application that supports using OpenKeyChain for authentication.

It would be great to have this in PasswordStore for ssh connection.

**Comment by alex005005** [comment] 2018-08-23 15:58
+1

**Comment by Mo-Et** [comment] 2018-09-07 10:00
+1

**Comment by alex005005** [comment] 2018-09-07 13:47
I'll see what I can do about it myself this weekend.

**Comment by Mo-Et** [comment] 2018-09-07 17:51
Awesome, i'd like to help but have never developed on Android yet. Any tips on which part of which code i should look at? Thanks

**Comment by zidhuss** [comment] 2018-09-19 09:50
Duplicate of #71

**Closed by zidhuss** 2018-09-19 09:50 UTC
