### ISSUE TITLE
Support android 11

### ISSUE THREAD

**Issue by Xgames123** [zeapo/Android-Password-Store#2644] opened 2023-08-10 15:04 UTC
### Is your feature request related to a problem? Please describe.

My phone (Samsung galaxy A50) run on android 11
It says on google play that there is no compatible version of the app for my phone.

### Describe the solution you'd like

Support android 11

### Describe alternatives you've considered

/

**Comment by msfjarvis** [comment] 2023-08-10 15:19
Duplicate of https://github.com/android-password-store/Android-Password-Store/issues/2587, https://github.com/android-password-store/Android-Password-Store/issues/2553, https://github.com/android-password-store/Android-Password-Store/issues/2533 and https://github.com/android-password-store/Android-Password-Store/issues/2417.

**Comment by Xgames123** [comment] 2023-08-10 15:19
I got it running by sideloading it
```adb install .\APS-free_v1.13.5.apk```

**Closed as not planned by msfjarvis** 2023-08-10 15:19 UTC
Labels: C-feature, S-awaiting-triage
