### ISSUE TITLE
Feature Request: Fingerprint instead of passphrase

### ISSUE THREAD

**Issue by FKatenbrink** [zeapo/Android-Password-Store#281] opened 2017-03-20 16:28 UTC
Hi,

I'd love to use my fingerprint sensor to unlock the store instead of my passphrase.
Would it be tough to implement this? And do you think it will compromise with the security?

**Comment by zeapo** [comment] 2017-03-20 16:39
duplicate of #262

**Closed** 2017-03-27 20:48 UTC
