### ISSUE TITLE
[BUG] ECONNREFUSED when trying to clone a GitHub private repo

### ISSUE THREAD

**Issue by UtkarshVerma** [zeapo/Android-Password-Store#2580] opened 2023-06-30 01:49 UTC
### Describe the bug

I can't clone my private GitHub repo. I have set up my SSH key appropriately. This is not working on the latest snapshot, and worked on the latest v1.x release. I had to switch to the snapshot because the release keeps pushing to `master` instead of `main`.

### Steps to reproduce

1. Open the app for the first time
2. Import SSH key
3. Add GitHub repo ssh URL `git@github.com:UtkarshVerma/passwords.git`

### Expected behavior

The repo should be cloned.

### Device information

- Device: Realme Narzo 50
- OS: Android 13
- App version: v2 snapshot https://github.com/android-password-store/Android-Password-Store/commit/2e0a40e82b602c5994e875acb7995b26c3e9355f

### Additional context

Logs
[log.txt](https://github.com/android-password-store/Android-Password-Store/files/11911904/log.txt)

**Comment by UtkarshVerma** [comment] 2023-06-30 01:52
Now that I realize, I was not prompted to add SSH key password at all. I don't see an option to set it as well.

**Comment by msfjarvis** [comment] 2023-06-30 04:57
Your SSH key's password is not saved, the app will ask for it when it needs to. `ECONNREFUSED` means the app failed to connect to GitHub at all, so it never got to using the SSH key and hence didn't prompt for a password. There's nothing to be fixed on our end here, it's an issue with your network.

**Closed as completed by msfjarvis** 2023-06-30 04:57 UTC
Labels: A-auth, S-unactionable

**Comment by UtkarshVerma** [comment] 2023-06-30 05:01
It's not an issue with my network. The previous version works just fine.

**Comment by msfjarvis** [comment] 2023-06-30 06:20
> It's not an issue with my network. The previous version works just fine.

I use SSH with a private repo for over a year and have no issues ¯\\_(ツ)_/¯

You can look at the log you uploaded and see that the error originates in the system networking stack.

**Comment by UtkarshVerma** [comment] 2023-07-01 03:23
Is there any way I can debug this? Because the v1.x of this app works for me, and I can browse the web without any issues. This is only happening in the snapshot build.

**Comment by xlucn** [comment] 2023-10-22 07:29
I have this issue as well. Here are some observations:

1. Same error:
   ```
   10-22 14:20:01.055 13215 13215 D PasswordStore: java.net.ConnectException: failed to connect to github.com/20.205.243.166 (port 22) from /:: (port 45498): connect failed: ECONNREFUSED (Connection refused)
   ```
   The rest is similar as the log attached by OP.
2. I cannot connect to other repos (even one that's hosted in my own school) with v2, either. The error is the same (ECONNREFUSED).
3. I can use the 1.x version to connect to github (or other repo).
4. I can use other apps (browser, github client) to connect to github (or other repo).
5. I can use `ping` or `nc` in android shell to connect to github (or other repo). The following all works
   ```
   ping github.com
   ping 20.205.243.166
   nc github.com 22
   nc 20.205.243.166 22
   ```

There seems to be something wrong with APS. How can I help further debug this?

---

Device information

- Device: OnePlus 8
- OS: LineageOS 20
- App version: Snapshot build of APS from revision https://github.com/android-password-store/Android-Password-Store/commit/a835021d6b0e4b96ea527b702a45b0d121882b8f, 
APS-freeRelease-2.0.0-SNAPSHOT.apk

**Comment by luigitropiano** [comment] 2023-11-06 11:29
I'm having the same issue as well. 

I'm running a bare git repository on my own home server, and I'm getting the same `ECONNREFUSED` error.
This only happens with the **snapshot** build however (both **free** and **non-free** releases), as the the **v1.x** is working fine.

---
Device information
- Device: OnePlus Nord
- OS: OxygenOS 12 (stock)
- App version: Snapshot build of APS from revision https://github.com/android-password-store/Android-Password-Store/commit/4c1076991b94c41891c0922d57e95559b1a1daee

**Comment by UtkarshVerma** [comment] 2023-11-23 07:30
I had two SIM cards on my device. The snapshot build works with carrier A but does not work with carrier B. This leads me to assume that Carrier B blocks SSH port 22. However, I also tried the alternative URL:
`git clone ssh://git@ssh.github.com:443/YOUR-USERNAME/YOUR-REPOSITORY.git`
And the same happens. Works with A, but doesn't with B.

Now I'm wondering why the v1.x build worked on Carrier B at all. Did something about the cloning mechanism change between v1.x and v2.x @msfjarvis?

Sorry for the mention. I just wasn't sure if you were getting notifications for this.

**Comment by msfjarvis** [comment] 2023-11-23 10:26
I _am_ getting notifications, I simply have nothing useful to add.

The app's networking stack has not meaningfully changed between V1 and V2, we still use the JGit library with an SSH transport provided by SSHJ, that's been the case for multiple years. The only major change since has been raising the app's target SDK, which tends to bring in breaking changes from the Android platform but I can't see anything in the past 3-4 Android releases that could alter the networking behavior in such a cryptic manner.

**Comment by UtkarshVerma** [comment] 2023-11-24 15:19
Oh, that does sound weird. Additionally, I also noticed today that I get the same error even over Wi-Fi. To sum it up:
- SIM 1 (BSNL) - Doesn't work
- SIM 2 (Jio) - Works
- Wi-Fi - Doesn't work

**Comment by czarkoff** [comment] 2024-01-07 14:24
I also have this issue on my OPPO Find N3 (ColorOS 13.2, firmware PHN110_13.2.0.203(CN01)) with all ssh servers that I tried, including a machine in my local network. F-Droid release of the app works just fine on the same device, and I can use ConnectBot to connect to the same servers woth no issues. Interestingly, on Xiaomi Redmi Note 8 Pro with CrDroid 9 I have no issues connecting to the same servers on the same network using the same snapshot version that causes me issues on the OPPO device.

P.S.: as far as I can tell, all of the confirmations in this thread are on OnePlus, Realme and (now) OPPO devices, which are essentially the same vendor using the same Android flavor (ColorOS). May it be an issue between SSHJ and ColorOS?

**Comment by czarkoff** [comment] 2024-02-10 17:00
FWIW I notice that the error message states IPv6 source address :: which is basically not an address at all. I have no IPv6 connectivity, so not having an IPv6 address makes sense in my case. Is there a way to force IPv4?

**Comment by luigitropiano** [comment] 2024-02-10 17:14
I confirm that the problem does not occur when synchronizing the repo from an IPv6 ready network. Forcing IPv4 may fix the issue.

Thanks @czarkoff for reporting this.

**Comment by msfjarvis** [comment] 2024-02-15 14:07
DNS resolution happens entirely within the Android networking stack outside the control of the app so the system probably thinks it has a good reason to pick IPv6 over IPv4. I don't believe it's possible to override that choice, but it might be possible to do IPv4-only DNS resolution within the app and pass along the resolved address to the SSH library instead.

**Comment by luigitropiano** [comment] 2024-02-20 09:14
@msfjarvis the old version of the app (v1.x) works fine though, even when connecting to a dual stack SSH server from an IPv4 only network.

**Comment by msfjarvis** [comment] 2024-02-20 09:21
> @msfjarvis the old version of the app (v1.x) works fine though, even when connecting to a dual stack SSH server from an IPv4 only network.

Like I've said before, there was no meaningful change to the app's networking stack since. I can't reproduce this bug, so if someone else wants to bisect the 1900 commits since the last 1.x release, please be my guest.

**Comment by LucyV4** [comment] 2024-03-10 15:20
I have had this same error since switching phones. And today have looked through the old commits and found which commit last worked on my phone (#2030 ). Removing or commenting out line 84 (see below) in Application.kt fixes the issue with getting the error ECONNREFUSED. 
```
.detectCleartextNetwork()
```
I am not sure what this is doing in the app and what it is needed for but I hope this narrows it down for you.

**Comment by msfjarvis** [comment] 2024-03-10 15:42
[StrictMode](https://developer.android.com/reference/kotlin/android/os/StrictMode?hl=en) is meant to detect common programming errors and is set to only log violations so I don't know why it would be related, but I'm not attached to it and will take a PR removing that specific check.

**Comment by msfjarvis** [comment] 2024-03-10 16:08
New snapshot is up, affected people can give it a shot and get back with their findings https://github.com/android-password-store/Android-Password-Store/releases/tag/latest

**Comment by LucyV4** [comment] 2024-03-10 17:45
For me it now fully works again, thank you!

**Comment by UtkarshVerma** [comment] 2024-03-11 00:44
Thanks a lot. It works for me now.
