### ISSUE TITLE
[BUG] Play store version not up to date

### ISSUE THREAD

**Issue by Mikilio** [zeapo/Android-Password-Store#2927] opened 2024-02-29 17:03 UTC
### Describe the bug

“This app isn't available for your device because it was made for an older version of Android” is being displayed on the Play Store. My version is 14. (Google ships newer versions earlier for pixel users)

As this never happens with other apps I use, I assume there must be a way to keep it up-to-date without just pure determination. Does the CI need improvement?

### Steps to reproduce

play store

### Expected behavior

play store install

### Device information

- Device: Google Pixel 7a
- OS: Android
- App version: 14
- Basebandversion: g5300q-230927-231102-B-11040898,g5300q-230927-231102-B-11040898
- Kernelversion: 5.10.177-android13-4-00003-ga7208022a7ea-ab10815828

**Comment by msfjarvis** [comment] 2024-02-29 17:33
Duplicate of #2764, #2669, #2663, https://github.com/android-password-store/Android-Password-Store/issues/2644, https://github.com/android-password-store/Android-Password-Store/issues/2587, https://github.com/android-password-store/Android-Password-Store/issues/2553, https://github.com/android-password-store/Android-Password-Store/issues/2533 and https://github.com/android-password-store/Android-Password-Store/issues/2417.

**Closed as not planned by msfjarvis** 2024-02-29 17:33 UTC
Labels: A-distribution, S-duplicate
