### ISSUE TITLE
[BUG] Onboarding view deals poorly with extremely low density screens

### ISSUE THREAD

**Issue by EasyVector** [zeapo/Android-Password-Store#1482] opened 2021-08-11 02:18 UTC
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, after I click the "let's go" button, **two buttons block a part of text on this new page**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.13.5, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts behind those two buttons. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the "let's go" button after starting this app
3.this error could be seen

**Screenshot**
<img src="https://user-images.githubusercontent.com/25502419/128959270-6e97c288-56eb-4f33-9375-97d8ef57f9cb.png" alt="Screenshot_1628565862 copy" width="250"/>

**Environment**

1. Version of Password Store: 1.13.5
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by Skrilltrax** [comment] 2021-08-11 07:55
Hey, it's a duplicate of #1262 and it has been fixed. You can try using the snapshot builds for now.

**Comment by SphericalKat** [comment] 2021-08-11 07:55
This has been fixed in #1271, and will be available in the next release.

**Closed as completed** 2021-08-11 07:55 UTC
Labels: C-bug, E-easy, P-low, A-UI-UX

**Comment by EasyVector** [comment] 2021-08-11 07:59
OK, I am very grateful for your response!
