### ISSUE TITLE
[BUG] git push - Internal Exception Occured

### ISSUE THREAD

**Issue by githlp** [zeapo/Android-Password-Store#1641] opened 2022-01-04 07:18 UTC
### Describe the bug

I am still able to git pull from my repo and also the "Hard reset to remote branch" works and local repo is reset to state of remote repo.

But when i change a pass entry in the android password store app and try to sync or git push, then i get the following exception:

```
Internal Exception occured

Attempt to write to field 'org.eclipse.jgit.internal.storage.pack.ObjectToPackorg.eclipse.jgit.internal.storage.pack.DeltaWindowEntry.object' on a null object reference
```

What can i do about this ?

### Steps to reproduce

see description above

### Expected behavior

git push should work as it did before

### Device information

- Device: Google Pixel 4a
- OS: GrapheneOS - Android version 12
- App version 1.13.5 (11350) from F-Droid

**Comment by msfjarvis** [comment] 2022-01-04 07:25
Duplicate of #1581 and #1623, this is GrapheneOS problem that was [unknowingly fixed](https://github.com/android-password-store/Android-Password-Store/issues/1581#issuecomment-1001230060) in our development branch.

**Closed as completed by msfjarvis** 2022-01-04 07:25 UTC
Labels: C-bug, S-invalid
