### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/PosixFilePermission;

### ISSUE THREAD

**Issue by fabianbuechler** [zeapo/Android-Password-Store#1032] opened 2020-08-20 13:55 UTC
**Describe the bug**
After the latest update v1.11.0 the app crashes right after starting it.

**To Reproduce**
1. Tap the app icon
2. App crashes

**Expected behavior**
App starts without crashing.

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi Note 4
 - OS: MIUI Global 11.0.2 Stable, Android 7.0 NRD90M
 - App version v1.11.0, updated 2020-08-18

**Additional context**
Stacktrace:

```java
java.lang.NoClassDefFoundError: Failed resolution of: Ljava/nio/file/attribute/PosixFilePermission;
        at org.eclipse.jgit.util.FS_POSIX_Java7.<clinit>(FS_POSIX_Java7.java:9)
        at org.eclipse.jgit.util.Java7FSFactory.detect(Java7FSFactory.java:7)
        at org.eclipse.jgit.util.FS.detect(FS.java:8)
        at org.eclipse.jgit.util.FS.<clinit>(FS.java:2)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:27)
        at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:1)
        at com.zeapo.pwdstore.utils.PasswordRepository.getRepository(PasswordRepository.kt:6)
        at com.zeapo.pwdstore.utils.PasswordRepository.initialize(PasswordRepository.kt:9)
        at com.zeapo.pwdstore.PasswordStore.checkLocalRepository(PasswordStore.kt:1)
        at com.zeapo.pwdstore.PasswordStore.onResume(PasswordStore.kt:4)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
        at android.app.Activity.performResume(Activity.java:6958)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3493)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.PosixFilePermission" on path: DexPathList[[zip file "/data/app/dev.msfjarvis.aps-1/base.apk", zip file "/data/app/dev.msfjarvis.aps-1/split_config.en.apk", zip file "/data/app/dev.msfjarvis.aps-1/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/dev.msfjarvis.aps-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        ... 23 more
        Suppressed: java.io.IOException: No original dex files found for dex location /data/app/dev.msfjarvis.aps-1/split_config.en.apk
                at dalvik.system.DexFile.openDexFileNative(Native Method)
                at dalvik.system.DexFile.openDexFile(DexFile.java:373)
                at dalvik.system.DexFile.<init>(DexFile.java:113)
                at dalvik.system.DexFile.<init>(DexFile.java:78)
                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:366)
                at dalvik.system.DexPathList.makeElements(DexPathList.java:327)
                at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
                at dalvik.system.DexPathList.<init>(DexPathList.java:126)
                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:62)
                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
                at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:522)
                at android.app.LoadedApk.getClassLoader(LoadedApk.java:555)
                at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1942)
                at android.app.LoadedApk.getResources(LoadedApk.java:773)
                at android.app.ContextImpl.<init>(ContextImpl.java:2078)
                at android.app.ContextImpl.createAppContext(ContextImpl.java:2023)
                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5410)
                at android.app.ActivityThread.-wrap2(ActivityThread.java)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
                ... 6 more
        Suppressed: java.io.IOException: No original dex files found for dex location /data/app/dev.msfjarvis.aps-1/split_config.xxhdpi.apk
                at dalvik.system.DexFile.openDexFileNative(Native Method)
                at dalvik.system.DexFile.openDexFile(DexFile.java:373)
                at dalvik.system.DexFile.<init>(DexFile.java:113)
                at dalvik.system.DexFile.<init>(DexFile.java:78)
                at dalvik.system.DexPathList.loadDexFile(DexPathList.java:366)
                at dalvik.system.DexPathList.makeElements(DexPathList.java:327)
                at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
                at dalvik.system.DexPathList.<init>(DexPathList.java:126)
                at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:62)
                at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
                at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
                at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
                at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:522)
                at android.app.LoadedApk.getClassLoader(LoadedApk.java:555)
                at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:1942)
                at android.app.LoadedApk.getResources(LoadedApk.java:773)
                at android.app.ContextImpl.<init>(ContextImpl.java:2078)
                at android.app.ContextImpl.createAppContext(ContextImpl.java:2023)
                at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5410)
                at android.app.ActivityThread.-wrap2(ActivityThread.java)
                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
                ... 6 more
```

Thanks for any information on how to fix this!
I use this app all the time, it's great!

**Comment by msfjarvis** [comment] 2020-08-20 14:01
Welp guess we did need R8 rules @FabianHenneke. Thanks for the report @fabianbuechler, I'll get on it.

**Comment by msfjarvis** [comment] 2020-08-20 14:03
@fabianbuechler can you test [this](https://dl.msfjarvis.dev/APS/aps-nonFree_1.12.0-SNAPSHOT.apk) version and see if it works?

**Comment by fmeum** [comment] 2020-08-20 14:15
@msfjarvis Do you have an idea why this is crashing only for some users? Both the release build I tested and the current Play Store version run just fine for me.

**Comment by msfjarvis** [comment] 2020-08-20 14:18
> @msfjarvis Do you have an idea why this is crashing only for some users? Both the release build I tested and the current Play Store version run just fine for me.

I'm not sure either, I updated one device from the Play Store and the other manually and they both work fine too.

**Comment by fabianbuechler** [comment] 2020-08-20 14:29
> @fabianbuechler can you test [this](https://dl.msfjarvis.dev/APS/aps-nonFree_1.12.0-SNAPSHOT.apk) version and see if it works?

This crashes aswell, but first shows a very similar error message **inside** (weird) the application somehow:

```java
java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.PosixFilePermission" on path: DexPathList[[zip file "/data/app/dev.msfjarvis.aps-2/base.apk"],nativeLibraryDirectories=[/data/app/dev.msfjarvis.aps-2/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.eclipse.jgit.util.FS_POSIX_Java7.<clinit>(FS_POSIX_Java7.java:9)
        at org.eclipse.jgit.util.Java7FSFactory.detect(Java7FSFactory.java:7)
        at org.eclipse.jgit.util.FS.detect(FS.java:8)
        at org.eclipse.jgit.util.FS.<clinit>(FS.java:2)
        at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:27)
        at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:1)
        at com.zeapo.pwdstore.utils.PasswordRepository.getRepository(PasswordRepository.kt:6)
        at com.zeapo.pwdstore.utils.PasswordRepository.initialize(PasswordRepository.kt:9)
        at com.zeapo.pwdstore.PasswordStore.checkLocalRepository(PasswordStore.kt:1)
        at com.zeapo.pwdstore.PasswordStore.onResume(PasswordStore.kt:4)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
        at android.app.Activity.performResume(Activity.java:6958)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3493)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3556)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
```

**Comment by msfjarvis** [comment] 2020-08-20 14:34
> > @fabianbuechler can you test [this](https://dl.msfjarvis.dev/APS/aps-nonFree_1.12.0-SNAPSHOT.apk) version and see if it works?
> 
> This crashes aswell, but first shows a very similar error message **inside** (weird) the application somehow:

These are testing builds so they ship with additional debug tooling like the stacktrace viewer you saw.
> 
> ```java
> java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.PosixFilePermission" on path: DexPathList[[zip file "/data/app/dev.msfjarvis.aps-2/base.apk"],nativeLibraryDirectories=[/data/app/dev.msfjarvis.aps-2/lib/arm64, /system/lib64, /vendor/lib64]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:74)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>         at org.eclipse.jgit.util.FS_POSIX_Java7.<clinit>(FS_POSIX_Java7.java:9)
>         at org.eclipse.jgit.util.Java7FSFactory.detect(Java7FSFactory.java:7)
>         at org.eclipse.jgit.util.FS.detect(FS.java:8)
>         at org.eclipse.jgit.util.FS.<clinit>(FS.java:2)
>         at org.eclipse.jgit.lib.BaseRepositoryBuilder.setup(BaseRepositoryBuilder.java:27)
>         at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:1)
>         at com.zeapo.pwdstore.utils.PasswordRepository.getRepository(PasswordRepository.kt:6)
>         at com.zeapo.pwdstore.utils.PasswordRepository.initialize(PasswordRepository.kt:9)
>         at com.zeapo.pwdstore.PasswordStore.checkLocalRepository(PasswordStore.kt:1)
>         at com.zeapo.pwdstore.PasswordStore.onResume(PasswordStore.kt:4)
>         at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
>         at android.app.Activity.performResume(Activity.java:6958)
>         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3493)
>         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3556)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
>         at android.app.ActivityThread.-wrap12(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:165)
>         at android.app.ActivityThread.main(ActivityThread.java:6375)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
> ```

And these exact builds work perfectly on our devices... Are you storing your passwords outside the local directory of the app? If so, what filesystem (ext4/f2fs/vfat) is that on?

**Comment by fmeum** [comment] 2020-08-20 19:28
@msfjarvis I think I know what's going wrong: [`PosixFilePermission`](https://developer.android.com/reference/java/nio/file/attribute/PosixFilePermission) has only been added in Oreo, but is used by JGit after some feature detection [here](https://github.com/eclipse/jgit/blob/2383cccf1226ad4c3140846517458de1e5283c27/org.eclipse.jgit.java7/src/org/eclipse/jgit/util/FS_POSIX_Java7.java#L84). This breaks the app on devices running Nougat and lower.

I think we should push a new version that reverts the addition of `jgit_java7` while we figure out how to resolve this properly. We could either fork `org.eclipse.jgit.java7` and remove all the arcane stuff we don't need (which is almost everything other than symlink support). Or we figure out how to polyfill `PosixFilePermission` on API levels 25 and lower only. Not sure whether that's possible though, on 26+ it would clash with the platform definitions.

**Comment by msfjarvis** [comment] 2020-08-20 19:35
> @msfjarvis I think I know what's going wrong: [`PosixFilePermission`](https://developer.android.com/reference/java/nio/file/attribute/PosixFilePermission) has only been added in Oreo, but is used by JGit after some feature detection [here](https://github.com/eclipse/jgit/blob/2383cccf1226ad4c3140846517458de1e5283c27/org.eclipse.jgit.java7/src/org/eclipse/jgit/util/FS_POSIX_Java7.java#L84). This breaks the app on devices running Nougat and lower.
> 
> I think we should push a new version that reverts the addition of `jgit_java7` while we figure out how to resolve this properly. We could either fork `org.eclipse.jgit.java7` and remove all the arcane stuff we don't need (which is almost everything other than symlink support). Or we figure out how to polyfill `PosixFilePermission` on API levels 25 and lower only. Not sure whether that's possible though, on 26+ it would clash with the platform definitions.

I think a fork seems more reasonable. I'll push out the revert.

**Comment by fabianbuechler** [comment] 2020-08-20 19:49
> > > @fabianbuechler can you test [this](https://dl.msfjarvis.dev/APS/aps-nonFree_1.12.0-SNAPSHOT.apk) version and see if it works?
> > 
> > This crashes aswell, but first shows a very similar error message **inside** (weird) the application somehow:
> 
> These are testing builds so they ship with additional debug tooling like the stacktrace viewer you saw.

Ah, I see. Saw the Leaks app after writing the comment.

> > 
> > ```java
> > java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.PosixFilePermission" on path: DexPathList[[zip file "/data/app/dev.msfjarvis.aps-2/base.apk"],nativeLibraryDirectories=[/data/app/dev.msfjarvis.aps-2/lib/arm64, /system/lib64, /vendor/lib64]]
> ... com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
> > ```
> 
> And these exact builds work perfectly on our devices... Are you storing your passwords outside the local directory of the app? If so, what filesystem (ext4/f2fs/vfat) is that on?

No, just the local dir on the phone's internal storage.

**Comment by msfjarvis** [comment] 2020-08-20 19:55
> > > > @fabianbuechler can you test [this](https://dl.msfjarvis.dev/APS/aps-nonFree_1.12.0-SNAPSHOT.apk) version and see if it works?
> > > 
> > > 
> > > This crashes aswell, but first shows a very similar error message **inside** (weird) the application somehow:
> > 
> > 
> > These are testing builds so they ship with additional debug tooling like the stacktrace viewer you saw.
> 
> Ah, I see. Saw the Leaks app after writing the comment.
> 
> > > ```java
> > > java.lang.ClassNotFoundException: Didn't find class "java.nio.file.attribute.PosixFilePermission" on path: DexPathList[[zip file "/data/app/dev.msfjarvis.aps-2/base.apk"],nativeLibraryDirectories=[/data/app/dev.msfjarvis.aps-2/lib/arm64, /system/lib64, /vendor/lib64]]
> > > ```
> > 
> > 
> > ... com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
> > > 
> > 
> > 
> > And these exact builds work perfectly on our devices... Are you storing your passwords outside the local directory of the app? If so, what filesystem (ext4/f2fs/vfat) is that on?
> 
> No, just the local dir on the phone's internal storage.

Thanks, we figured it out. It's caused by our recently merged support for symlinks which tries to use some code that didn't exist before Android 8 and thus crashes on your phone. In about 10 to 20 minutes I'll push out v1.11.1 that will fix the issue.

**Comment by fabianbuechler** [comment] 2020-08-20 19:58
> Thanks, we figured it out. It's caused by our recently merged support for symlinks which tries to use some code that didn't exist before Android 8 and thus crashes on your phone. In about 10 to 20 minutes I'll push out v1.11.1 that will fix the issue.

That's great, thanks a lot!
You guys are on the fast track :-)

👍

**Closed as completed** 2020-08-20 20:27 UTC
