### ISSUE TITLE
[FEATURE] Allow user to add custom keys (not pgp key)

### ISSUE THREAD

**Issue by rEnr3n** [zeapo/Android-Password-Store#1478] opened 2021-08-06 07:41 UTC
**Is your feature request related to a problem? Please describe.**
The password file organization I use is `work/example.org/john@doe.org(.gpg)`.

All of my entries contain things like `URL: https://example.com/`, `Tag: xxx`. APS doesn't officially recognize them and puts them all in `Extra content:`. If I need to copy one of the values (e.g. URL), I would need to hold my finger on the string I want to copy hoping that it selects the text properly. This is not as simple when the `Extra content:` consumes more space than the screen size. Holding my finger on one spot can select multiple lines. Trying to adjust the selection can get it jerky. I end up being frustrated.

**Describe the solution you'd like**
Allow users to add their own keys like `URL:`, `Tag:`, etc. so that they can be displayed and copied independently. Unrecognized keys should still go to `Extra content:`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by msfjarvis** [comment] 2021-08-06 08:01
This is a duplicate of #1191 and #1412, which was fixed but hasn't been released yet. If you want immediate access to the functionality you can use the [snapshot builds](https://android-password-store.github.io/docs/users/release-channels) but beware that downgrading back to the Play Store version will require uninstalling and reinstalling from the Play Store.

**Closed as completed by msfjarvis** 2021-08-06 08:01 UTC
Labels: C-feature, S-invalid
