### ISSUE TITLE
[BUG] Pressing back returns to the previous screen with search results

### ISSUE THREAD

**Issue by advortsov** [zeapo/Android-Password-Store#1273] opened 2021-01-08 10:38 UTC
**Describe the bug**
Pressing < ("Back" button) returns to the previous fuzzy search results screen instead of the home screen

**To Reproduce**
1. Click on 'Search' on the home screen
2. Enter the name of the application ("briar" on screens), the entry for which has nested users with passwords
3. Tap to search result with nested entries
4. Press < ("Back" button)
5. Get to home screen (scr 1)

**Expected behavior**
Pressing < ("Back" button) returns to the previous fuzzy search results screen (scr 2)

**Screenshots**
scr 1
![photo5458380392554934239](https://user-images.githubusercontent.com/12611411/104005734-a2133e80-51b6-11eb-83dd-f6bbea50a86c.jpg)

scr 2
![photo5458380392554934238](https://user-images.githubusercontent.com/12611411/104005791-b3f4e180-51b6-11eb-9d6f-5ac435963a0d.jpg)

**Device information:**
 - Device: Xiaomi Redmi 4X
 - OS: LineageOS 16.0-20201125-NIGHTLY-santoni
 - Password Store 1.13.2

**Comment by msfjarvis** [comment] 2021-01-08 11:25
This is intended behaviour AFAIK, @fmeum would be able to confirm.

**Comment by NANASHI0X74** [comment] 2021-01-08 12:38
chiming in because I happened to see this and have had a related gripe:

I think it's strange that the android back button doesn't do the same as the back arrow button at the top left of the app.
This is the behavior for both, when viewing a password entry after navigating there via serch results:

1. back button goes back to search
2. back arrow goes back to "home" screen

imo I think both should do the same thing which is the former, to go back to the search results.

**Comment by msfjarvis** [comment] 2021-01-08 12:43
> chiming in because I happened to see this and have had a related gripe:
> 
> I think it's strange that the android back button doesn't do the same as the back arrow button at the top left of the app.
> This is the behavior for both, when viewing a password entry after navigating there via serch results:
> 
> 1. back button goes back to search
> 2. back arrow goes back to "home" screen
> 
> imo I think both should do the same thing which is the former, to go back to the search results.

You're right, but it's a separate bug. I'll get it sorted.

**Comment by NANASHI0X74** [comment] 2021-01-08 12:47
😅 thanks

**Comment by fmeum** [comment] 2021-01-12 05:48
> This is intended behaviour AFAIK, @fmeum would be able to confirm.

This is expected behavior, but of course it is not set in stone. 
@advortsov Could you briefly describe why you would prefer the back button to behave differently here?

**Comment by msfjarvis** [comment] 2021-01-29 08:56
@advortsov can you please answer the question above so we can make a decision here?

**Comment by advortsov** [comment] 2021-01-29 09:43
Well I think this is a matter of habit. I think this option is more logical.

**Comment by msfjarvis** [comment] 2021-01-29 10:00
> Well I think this is a matter of habit. I think this option is more logical.

Returning users to their search results is also logical in that it lets them pick a different entry if one was selected on accident, without having to re-enter the search query. If you make your case in some more detail it'd be helpful in coming to an agreement :)

**Comment by msfjarvis** [comment] 2021-04-04 06:33
Appears the OP has abandoned this, closing.

**Closed as completed by msfjarvis** 2021-04-04 06:33 UTC
Labels: C-bug, S-awaiting-triage, A-UI-UX
