### ISSUE TITLE
[BUG] Cannot synchronize repo if branch is named "main" even after changing branch name in settings

### ISSUE THREAD

**Issue by AkechiShiro** [zeapo/Android-Password-Store#2273] opened 2022-11-26 12:35 UTC
### Describe the bug

My bug is similar to #147, and related to #1785

The error, I'm getting, is 
> An exception occurred during a git operation: Could not get advertised Ref for branch `master`.

My repo has no branch `master` but only a branch `main`, is this hard-coded or intended that the only branch that will get synced is `master` ?

Workaround:
I managed to sync : 
1. Changing the branch name to `main` in the settings according to #977.
 2. In settings `Git local configuration`, press `hard reset of the remote branch`. 
 3. that still did not make the error go away, but did synchronize the repo it seems.
 4. I see that in the `Git local configuration` -> `Utilities` still shows `on branch master` despite the `main` branch being configured in `Git server settings`.

### Steps to reproduce

1. Go to Git server
2. Rename your branch from master to any other name.
3. Changing or not changing the `Git server settings` ⇾ `branch` to `main` instead of `master` as shown in #977
4. Go to Password Store App
5. Try and synchronize.
6. See error

### Expected behavior

I believe the most correct behavior should be to ask the user which branch he wishes to synchronize, or to synchronize the only branch that exist in the repo.

In my case I only have one branch `main` and so it should be selected instead of trying `master` by default.

Another issue is that in `Git local settings` ⇾ `Utilities`, it should be shown `on branch main`, not `master` anymore.

### Device information

- Device: Xiaomi Poco F3
- OS: stock ROM Android version 13
- App version: 1.13.5

### Additional context

I've noticed a second issue, on a device where I already synced when the `master` branch existed, now after having renamed the `master` to `main`, it no longer works and shows :
> A git exception occured: Could not get advertised Ref for branch refs/heads/master 

I believe this is similar to #1785, I can open a separate issue for the step to reproduce it.

**Comment by msfjarvis** [comment] 2022-11-26 15:54
Fixing this is proving to be much more involved than I expected but I think I have a good grasp on how to pull it off.

The gist of the problem is that JGit does not throw an error when you try to pass in an invalid remote branch and instead just swallows it, which makes it near impossible to detect on the app side.

**Comment by msfjarvis** [comment] 2022-11-27 07:56
This is fixed with #2275, the change will be available in the [snapshot builds](https://docs.passwordstore.app/docs/users/release-channels) in around 15 minutes after the PR is merged. It's recommended to go through the [unreleased section of the changelog](https://github.com/android-password-store/Android-Password-Store/blob/develop/CHANGELOG.md#unreleased) to get a sense of what has changed between 1.13.5 and 2.0.0.

**Closed as completed** 2022-11-27 08:11 UTC
Labels: C-bug, E-medium, P-high, A-Git

**Comment by AkechiShiro** [comment] 2022-12-10 10:18
Hey @msfjarvis I can't seem to decrypt my password with the new app, I don't understand how can I use pgpainless ? I've done the sync and then I try to read a password, it asks me for a password, I enter the master password, it tells me "Incorrect password" no matter what.

I also have no idea how to enroll my PGP key with the new backend, is there any documentation on how to proceed ?

**Comment by msfjarvis** [comment] 2022-12-10 10:28
> Hey @msfjarvis I can't seem to decrypt my password with the new app, I don't understand how can I use pgpainless ? I've done the sync and then I try to read a password, it asks me for a password, I enter the master password, it tells me "Incorrect password" no matter what.
> 
> I also have no idea how to enroll my PGP key with the new backend, is there any documentation on how to proceed ?

There's still a lot left to do in terms of UX and error handling for the new backend. To add your key you'll need to export your PGP secret key to a file and move it to your device then go to settings > pgp settings > key manager and press the `+` button at the bottom right to find and import it. Things should work fine after that.
