### ISSUE TITLE
ed25519 key support

### ISSUE THREAD

**Issue by lol768** [zeapo/Android-Password-Store#336] opened 2017-09-04 11:17 UTC
Am I correct in thinking these aren't supported currently? (They don't appear to import)

**Comment by chrboe** [comment] 2017-09-14 14:20
Duplicate of #134

**Comment by lol768** [comment] 2017-09-14 14:22
Cheers

**Comment by c-e-p-x-u-o** [comment] 2018-03-28 21:46
@zeapo should be closed, right?

**Closed** 2018-03-29 08:08 UTC
