### ISSUE TITLE
unable to push from android to remote repo: Error: push not permitted [BUG]

### ISSUE THREAD

**Issue by eklebanow** [zeapo/Android-Password-Store#1001] opened 2020-08-10 03:53 UTC
Since changing to a new phone I am unable to push from phone to bare passwordstore repo on bitbucket.  

I can pull from remote repo....I cannot synchronize or push

The error message I get is as follows: Error occurred during the push operation: git@bitbucket.org;klebane/password-store.bare.git: push not permitted.  Caused by org eclipese.jgit.errors. transportexception: git@bitbucket.org:klebane/password_store:bare.git push not permitted.

I am using SSH. I have a google pixel phone.

**Comment by msfjarvis** [comment] 2020-08-10 06:47
This is almost certainly caused by the same problem as #1002 so I'll close this one.

**Closed as completed** 2020-08-10 06:47 UTC

**Comment by eklebanow** [comment] 2020-08-10 18:32
I do not believe it should be closed.....
In the new version bug 1002 problem is that I cannot get git settings correct for bitbucket syntax

I can get the git settings correct in the legacy version of android store but I cannot synchronize or push.  I can pull from the remote.

Here is a screenshot of the error message I get when I try to push from the phone to bitbucket (the remote):
[Screenshot (Aug 10, 2020 11_29_07).pdf](https://github.com/android-password-store/Android-Password-Store/files/5052657/Screenshot.Aug.10.2020.11_29_07.pdf)

What is causing this error? Everything was working...now it is not and I do not think I changed anything

1002 is a problem entering correct git settings for bitbucket.  1001 is a different problem....the correct syntax for bitbucket.org is entered but pushing is not allowed....

**Comment by fmeum** [comment] 2020-08-11 07:26
"push not permitted" is an error that originates from Bitbucket after successful authentication, so I doubt that it has anything to do with Password Store. Please verify that your SSH key is allowlisted for write operations and check whether regular git shows a similar error message.
