### ISSUE TITLE
[BUG] Unable to decrypt

### ISSUE THREAD

**Issue by RodAlc24** [zeapo/Android-Password-Store#3228] opened 2024-09-22 18:55 UTC
### Describe the bug

Being on the screen with the list of all the entries, when I click on the password I want to decrypt, instead of asking for the password it returns me to the same place.

### Steps to reproduce

1. Open the app
2. Select the entry you want to decrypt
3. It appears for a second the screen with the title of the entry, but before it asks for the password it crashes, returning to the previous screen

### Expected behavior

It asks for the password and it decrypts the entry.

### Device information

- Device: honor 10 lite
- OS: Android 10
- App version: nonFree 2.0.0 SNAPSHOT (the last one 22/09/2024)

### Additional context

[log.txt](https://github.com/user-attachments/files/17090867/log.txt)

Edit: It may be related with #3227, but i don't get any error.

**Comment by msfjarvis** [comment] 2024-09-22 19:02
Based on the log this is a duplicate of #3214 which I'm already investigating, please subscribe to that issue for updates.

**Closed as not planned by msfjarvis** 2024-09-22 19:02 UTC
Labels: C-bug, A-PGPainless, S-duplicate

**Comment by RodAlc24** [comment] 2024-09-22 19:12
Ok, thanks
