### ISSUE TITLE
[FEATURE] show only exact search results

### ISSUE THREAD

**Issue by 532910** [zeapo/Android-Password-Store#1200] opened 2020-11-12 08:16 UTC
**Is your feature request related to a problem? Please describe.**
Not related to any problem, just a feature request.

**Describe the solution you'd like**
A control to show only exact search results, so that the app could behave the same as `pass find` does.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by msfjarvis** [comment] 2020-11-12 08:22
~~Closing as duplicate of #1197~~

**Comment by 532910** [comment] 2020-11-12 08:37
This is not a duplicate, this is a feature request for the control to disable fuzzy search.

**Comment by msfjarvis** [comment] 2024-10-12 15:59
I have made the decision to archive the project for reasons outlined [here](https://github.com/android-password-store/Android-Password-Store/discussions/3260).

This issue is being closed to ensure everyone subscribed to it is made aware of this change in the app's maintenance status.

**Closed as not planned by msfjarvis** 2024-10-12 15:59 UTC
Labels: hacktoberfest, E-easy, P-medium, C-feature, A-pass-list
