### ISSUE TITLE
Adding new passwords/moving existing ones don't update in git

### ISSUE THREAD

**Issue by hughdavenport** [zeapo/Android-Password-Store#299] opened 2017-05-22 01:09 UTC
I'm adding new passwords and they don't show up in the git commit (it is empty, just the title). Moving just deletes it. Deleting works as expected.

**Comment by zeapo** [comment] 2017-05-22 06:58
Hi, thanks for the report. Which version are you using?
This has been fixed in .58 in 824845bf41227c9ee0891f6d0299efe0f067ce00

If it's still not fixed for you, could you provide a way to reproduce this?

**Comment by hughdavenport** [comment] 2017-05-22 07:11
Yep i got .58 from fdroid. I'll see if i can create a dummy repo and try reproduce

**Comment by zeapo** [comment] 2017-05-22 07:12
would be great thx.

I will try to reproduce it too :)

**Comment by qv1x0te** [comment] 2017-05-22 09:26
I’m having the same problem, version 1.2.0.58 from Google Play

**Comment by Aventura5** [comment] 2017-05-26 14:47
I have the same problem, 1.2.0.58 from F-Droid. I tried deleting and re-cloning the repo but no luck. It commits and syncs but the commit is empty.

**Comment by zeapo** [comment] 2017-05-26 15:00
:(

I will try to reproduce it this weekend.

Thanks

**Comment by jayme-github** [comment] 2017-05-28 15:49
Same here with .59 from F-Droid.

**Comment by zeapo** [comment] 2017-05-28 15:53
Looks like it has been introduced in 58...

**Comment by jayme-github** [comment] 2017-05-28 16:05
> Looks like it has been introduced in 58...

Confirmed. Reverting to .57 fixes this for me.

**Comment by zeapo** [comment] 2017-05-28 16:44
fixed, sorry guys, that was a dumb copy/paste 👎

**Closed by zeapo** 2017-05-28 16:44 UTC
Labels: bug
