### ISSUE TITLE
[BUG] Error while syncing with GPG-key

### ISSUE THREAD

**Issue by denkorzh** [zeapo/Android-Password-Store#1323] opened 2021-02-24 09:19 UTC
**Describe the bug**
Cannot sync local repo with the remote one using gpg-key authentication method. This seems to be related to the latest Openkeychain update though I am not sure.

**To Reproduce**
1. Go to the main window
2. Click on Pull/Sync repo
3. Select your gpg key from openkeychain
4. See error `Request SshPublicKeyRequest failed: Error converting public key to SSH format: Unknown key algorithm`

**Expected behavior**
The repo should be synced

**Device information (please complete the following information):**
I have the same issue on two devices
- 1
  - Device: Samsung S21+ 5G
  - OS: Android 11
  - App version 1.13.2
- 2
  - Device: Honor V10 (BKL-L09)
  - OS: Android 10
  - App version 1.13.2

**Comment by msfjarvis** [comment] 2021-02-24 09:21
Duplicate of #1272, this is on track for being fixed in the next version of OpenKeychain.

**Closed as completed** 2021-02-24 09:22 UTC
Labels: C-bug, S-awaiting-triage
