### ISSUE TITLE
[BUG] Synchronize repository fails if `master` branch is missing

### ISSUE THREAD

**Issue by mindgrep** [zeapo/Android-Password-Store#1785] opened 2022-03-14 00:31 UTC
### Describe the bug

After fixing issue #298 password store is able to sync with a git branch other than `master`.

However, if the `master` branch is deleted, the sync fails with the message:
```
Could not get advertised Ref for branch refs/heads/master
```

### Steps to reproduce

1. Set up password store to sync with a git repository, on a branch other than `master` e.g. `main`
2. Delete the `master` branch on the (remote) git repo if it exists
3. Set the default branch in the repo settings to `main`
4. Synchronize with the git repo from the android app

### Expected behavior

The synchronization should succeed.

### Device information

- Device: Google Pixel 5a
- OS: Android 12
- App version: 1.13.5

**Comment by msfjarvis** [comment] 2022-03-14 11:35
Reproduced, thanks for the report.

**Comment by skewballfox** [comment] 2022-07-18 14:20
open to a PR for this?

**Comment by msfjarvis** [comment] 2022-07-18 14:21
> open to a PR for this?

Absolutely!

**Comment by skewballfox** [comment] 2022-07-18 14:26
sweet. May take me a second, new to Kotlin and still getting my environment setup, but I should have a fix in the next couple of days worst case.

**Comment by skewballfox** [comment] 2022-07-18 14:57
hey, stupid question. I've looked at the kotlin cheatsheet, list of operators, etc. but I cannot seem to find documentation for this syntax: 
```kotlin
val storedConfig = repository!!.config
```
what is `!!` doing? 
I'm assuming `!!` is trying to do some kind of lazy initialization. but for some reason it that syntactic pattern seems hard to find via search results. 

also do you know of a community discord for kotlin?

**Comment by msfjarvis** [comment] 2022-07-18 15:06
> hey, stupid question. I've looked at the kotlin cheatsheet, list of operators, etc. but I cannot seem to find documentation for this syntax:
> 
> ```kotlin
> val storedConfig = repository!!.config
> ```
> 
> what is `!!` doing? I'm assuming `!!` is trying to do some kind of lazy initialization. but for some reason it that syntactic pattern seems hard to find via search results.

https://kotlinlang.org/docs/null-safety.html#the-operator

> 
> also do you know of a community discord for kotlin?

AFAIK there isn't one. They have an official Slack though: https://slack.kotlinlang.org/

**Comment by skewballfox** [comment] 2022-07-18 17:52
so I built the app with the free debug symbols, and tested it with my personal repo for passwords. I created a different branch `test`, and temporarily deleted master, and synced before and after master was deleted. sync worked, no errors were reported. 

could this have been an error generated by one of the dependencies which is now fixed?

**Comment by msfjarvis** [comment] 2022-07-18 18:00
It's pretty unlikely a dependency update fixed it since we have not updated JGit in years but if it can't be reproduced we can just close the issue and let people open a new issue if they encounter it. Thanks for investigating!

**Closed as completed by msfjarvis** 2022-07-18 18:00 UTC
Labels: C-bug, E-medium, P-high, A-Git, S-help-wanted
