### ISSUE TITLE
[BUG] Exclamation point in key fingerprint

### ISSUE THREAD

**Issue by kirelagin** [zeapo/Android-Password-Store#1360] opened 2021-03-28 17:50 UTC
This is, in some sense, related to #998. Let me also say right away that I tried the 2021-03-26 snapshot and this issue is present there.

My `.gpg-id` contains two full fingerprints _followed by `!`_. The reason for this is that I have one PGP key with two encryptions subkeys: one for everyday use, one for backups. The exclamation point at the end tells GnuPG to use this exact subkey rather than doing its default lookup procedure, which would not result in what I want.

From the discussion at the issue referenced above, I understood that OpenKeychain allows full fingerprint as the key identifier, so, on the surface, it looks like the only required change would be to allow the trailing exclamation point when parsing `.gpg-id`.

I would also like someone more familiar with OpenKeychain to confirm that it will do the right thing when given the full key fingerprint (rather than doing GnuPG-like lookup via primary key).

**Comment by kirelagin** [comment] 2021-03-28 18:09
Ok, I have now given a more careful read to the middle of that issue above and found comments from people who seem to have the same setup as mine. It seems to follow from the discussion that OpenKeychain, indeed, does not allow forcing a specific subkey for encryption, so, I guess this issue can be used as another justification for #1195.

**Comment by mist** [comment] 2021-04-12 16:24
I am suffering the same problem. It worked before the big UI-overhaul some time ago, or so I think, as I did not check if I could set  my subkey in `.gpg-id` and it probably was just by accident the correct key.

**Comment by Myridium** [comment] 2021-07-04 15:13
I created a duplicate issue on this which I'm going to close. I'll paste here my version of this issue which may add more information:

Password-store for Android does not recognise a specific subkey selection, e.g. `141E0FE3342C4914!` (note the exclamation mark at the end). The `password-store` program for UNIX does accept this, and in fact this feature is necessary in order to encrypt for a *specific set of subkeys* associated with a given identity. If you use only `141E0FE3342C4914` then `gpg` will select the newest encryption key it finds for the identity associated with `141E0FE3342C4914`.

This feature is necessary in order to manage multiple encryption keys on different devices, which are aware of each other's public encryption keys as part of the user's identity. 

**To Reproduce**
Steps to reproduce the behavior:
1. On GNU/Linux run `pass init <myencryptionkey_in_0x_long_format>!` including the exclamation mark at the end.
2. Synchronise `password-store` for Android with the created `git` repository.
3. Try creating a new password and saving it, as this is the step where the program tries to encrypt using the key recorded in `.gpg-id`. When you click the save button, you will receive the error `Found .gpg-id, but it contains an invalid key ID, fingerprint or user ID`

**Expected behavior**
`password-store` for Android should recognise the encryption key contained in `.gpg-id` and pass the encryption key straight to `gpg` with the exclamation mark on the end. `gpg` understands that a key with an exclamation mark at the end means to encrypt *specifically for the given key*, instead of the stupid default behaviour (where selecting the most recent encryption key available which is associated with the same identity).

**Device information (please complete the following information):**
App version is `1.13.4`.

**Additional context**
Specific key selection is supported by both `gpg` and `password-store` on the desktop application. It should be supported here too. It's possible that all that needs to be done is to relax the error-checking of `.gpg-id` to allow keys with an exclamation mark at the end. I don't think any special treatement is required to handle these specific keys. They just need to be passed to `gpg` including the exclamation mark at the end.

**Comment by msfjarvis** [comment] 2021-07-04 18:42
The app does not directly use GnuPG, so we can't pass anything to it. I'd like to know a bit more about this entire mechanism before I do any implementation work.

Given a key with two encryption subkeys `ABCDEF...XYZ` and `012345...9` where the latter is newer, which subkey(s) should be selected if:

- `.gpg-id` contains `ABCDEF...XYZ`
- `.gpg-id` contains `012345...9`
- `.gpg-id` contains `ABCDEF...XYZ`

**Comment by Myridium** [comment] 2021-07-04 20:24
Is that a typo @msfjarvis or did you intentionally omit the B?

Assuming it was a typo: I don't know what the OpenKeychain behaviour is, but `password-store` desktop passes the key straight to `gpg`, which will throw key away and pick the newest one associated with the same identity. When I say "newest" I'm not sure what the actual specific criteria are.

For example, I had three different encryption keys associated with the same identity, and added then to `.gpg-id` with `pass init`. Passwords are encrypted only for the newest of the three, because that's the key `gpg` encrypts for unless you use the exclamation mark.

**Comment by msfjarvis** [comment] 2021-07-04 20:31
> Is that a typo @msfjarvis or did you intentionally omit the B?
> 

yeah it's a typo, the bane of trying to write things on my phone :)

> Assuming it was a typo: I don't know what the OpenKeychain behaviour is, but `password-store` desktop passes the key straight to `gpg`, which will throw key away and pick the newest one associated with the same identity. When I say "newest" I'm not sure what the actual specific criteria are.

Yeah I'm not concerned with OpenKeychain's behavior, I just want to know what the expectations are from GnuPG on the desktop so I can match it. We're already adding support for an alternative OpenPGP implementation in #1441 and #1446, which we intend to make the sole GnuPG provider in v2.0.

> 
> For example, I had three different encryption keys associated with the same identity, and added then to `.gpg-id` with `pass init`. Passwords are encrypted only for the newest of the three, because that's the key `gpg` encrypts for unless you use the exclamation mark.

So given those three encryption subkeys, having the exclamation mark tells GnuPG to use the subkey whose ID is in `.gpg-id` without trying to use any of its "newest" logic, right?

**Comment by Myridium** [comment] 2021-07-04 20:39
@msfjarvis I dug into the source code of `password-store` a little while back and if I remember correctly, all it does is read `.gpg-id`, extract the keys as space-separated words, and then pass those as arguments to the `gpg` encryption command which I think was `gpg -e key1 -e key2 -e key3 .....`. The `.gpg-id` file is not something standard to gpg I guess, but just a file by password-store to store the list of keys.

I found that `password-store` appears to be agnostic to what those keys are, that can have exclamation marks or even invalid characters in them. It just cares about the space separation, and uses this to form the separate `-e` parameters it gives to `gpg`.

It's been a little while since I looked into it so sorry if any of this is inaccurate, this is how I remember it.

**Comment by Myridium** [comment] 2021-07-04 20:42
When you use `gpg -e key1 -e key2 ....` my guess is that GPG looks up each key individually. If the key does not have an exclamation mark, then it thinks you're really just trying to look up someone's identity, I think you could also use a name or email address. So even if you give it 3 different keys, each one is resolved to the same identity, which has the same default encryption key, which is the most recent.

The exclamation mark on the end of the key asserts that you really mean this specific key and NOT the identity associated with it.

**Comment by msfjarvis** [comment] 2022-04-08 19:27
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).

**Closed as completed by msfjarvis** 2022-04-08 19:27 UTC
Labels: C-bug, E-hard, P-medium, A-PGP, S-help-wanted
