### ISSUE TITLE
[FEATURE] Support installation on Android 13

### ISSUE THREAD

**Issue by Minipada** [zeapo/Android-Password-Store#2587] opened 2023-07-05 11:51 UTC
### Is your feature request related to a problem? Please describe.

I want to install the application on Android 13

### Describe the solution you'd like

I want to install the application on Android 13 on the store

### Describe alternatives you've considered

Or through any other way

**Comment by msfjarvis** [comment] 2023-07-05 12:07
Duplicate of #2553, #2533 and #2417.

There's a reason the issue template asks you to search existing issues :)

**Closed as not planned** 2023-07-05 12:07 UTC
Labels: A-distribution, S-duplicate
