### ISSUE TITLE
Found .gpg-id but it contains a short hex id which is not supported

### ISSUE THREAD

**Issue by AkechiShiro** [zeapo/Android-Password-Store#2919] opened 2024-02-26 23:52 UTC
### Describe the bug

Latest APS release, clicking on any password shows the following issue : 
Found .gpg-id but it contains a short hex id which is not supported

### Steps to reproduce

1. Clone repo
2. Import private key
3. Sélect a password élément of the store

### Expected behavior

Maybe there should be a few note on this issue and how to solve it (can we just export our private key in others format) or should we be busy.

### Device information

- Device: Google Pixel 6 Pro
- OS:  Android R
- App version: [e.g. 1.13.5]

**Comment by msfjarvis** [comment] 2024-02-27 02:58
The issue isn't with your private key but the format in which its ID is entered into the `.gpg-id` file in your store. The simplest solution is to get the full hexadecimal ID of your key and run `pass init <keyid>` (without the angle brackets) on your computer to set it up correctly.

**Comment by AkechiShiro** [comment] 2024-02-27 06:39
Will do that but then I will need to sync the .gpg-id file to which path ? On my phone ?

**Comment by AkechiShiro** [comment] 2024-02-27 08:12
If my password store is already set, is there any way I can tweak the .gpg-id file ? @msfjarvis

**Comment by msfjarvis** [comment] 2024-02-27 08:14
> If my password store is already set, is there any way I can tweak the .gpg-id file ? @msfjarvis 

Running init over an existing store is non-destructive, but you can always just edit and commit the file yourself.

**Comment by msfjarvis** [comment] 2024-02-27 08:14
> Will do that but then I will need to sync the .gpg-id file to which path ? On my phone ? 

If it's a Git repository you should be able to pull the changes once you push them from your PC.

**Comment by msfjarvis** [comment] 2024-02-29 05:37
Closing since this is not a bug.

**Closed as not planned by msfjarvis** 2024-02-29 05:37 UTC
Labels: C-question

**Comment by AkechiShiro** [comment] 2024-03-07 21:45
This was indeed fixed by changing the gpg id, thanks !
