### ISSUE TITLE
[FEATURE] TOTP authentication with the code

### ISSUE THREAD

**Issue by dfrost16** [zeapo/Android-Password-Store#1325] opened 2021-02-24 18:49 UTC
Password Store supports TOTP which works by scanning the code, meanwhile other alternative such as Google authenticator app supports both scan and manual input of the totp code is it possible to implement it on password Store would be really convinent

**Comment by msfjarvis** [comment] 2021-02-24 21:12
Duplicate of #1311, has been fixed by #1320. Please search through closed issues as well before filing new ones.

**Closed as completed** 2021-02-24 21:13 UTC
Labels: C-feature, S-invalid
