### ISSUE TITLE
[BUG] Strange Behavior in Phishing Resistant Search

### ISSUE THREAD

**Issue by colonelpanic8** [zeapo/Android-Password-Store#1452] opened 2021-07-05 22:57 UTC
Perhaps this is by design, but it seems that when Phishing Resistant search is enabled, I must type the FULL name of the password before I get any results:

![NoResults](https://user-images.githubusercontent.com/1246619/124522883-f1c37300-ddb1-11eb-9ca2-9e41a3afe22d.jpg)
![Screenshot_20210705-165140](https://user-images.githubusercontent.com/1246619/124522888-f8ea8100-ddb1-11eb-915e-0778417954c5.jpg)

Is this by design? My intuition about what this option would provide is e.g. disallowing different capitalization or substituted characters.

**Comment by msfjarvis** [comment] 2021-07-06 04:04
This is by design as of now and unlikely to change in the immediate future. We can revisit this closer to the 2.0 release, after our larger refactors are out of the way.

**Comment by msfjarvis** [comment] 2022-04-08 19:27
Closing as part of [issue tracker cleanup](https://github.com/android-password-store/Android-Password-Store/discussions/1836).

**Closed as completed by msfjarvis** 2022-04-08 19:27 UTC
Labels: C-bug, E-medium, P-low, A-UI-UX, S-help-wanted
