### ISSUE TITLE
[FEATURE] Support for new meta data format used by gopass

### ISSUE THREAD

**Issue by senilio** [zeapo/Android-Password-Store#1124] opened 2020-09-29 18:53 UTC
**Is your feature request related to a problem? Please describe.**
gopass devs have implemented a new meta data format for secrets, where all secrets start with the line ```GOPASS-SECRET-1.0```. This line is picked up by Android Password Store as the actual password.

More info on the new format here: https://github.com/gopasspw/gopass/blob/master/docs/features.md#mime-secrets

**Describe the solution you'd like**
It would be awesome if support for this new format could be implemented in APS, so gopass and APS will continue to play nice together.

**Describe alternatives you've considered**
The workaround to this is to open the secret in APS, but manually select and copy the part of the secret you're interested in.

**Comment by msfjarvis** [comment] 2020-09-29 18:56
Duplicate of https://github.com/android-password-store/Android-Password-Store/issues/1055, I've answered it there.

**Closed as completed by msfjarvis** 2020-09-29 18:56 UTC
