### ISSUE TITLE
BUG - no longer available for recent Android versions

### ISSUE THREAD

**Issue by rbroggi** [zeapo/Android-Password-Store#3114] opened 2024-07-06 07:12 UTC
![Screenshot_20240706-091124.png](https://github.com/android-password-store/Android-Password-Store/assets/5781339/2d68c89c-596e-4c23-8bdc-8109c6227ccc)

Seems like this app is no longer available for recent Android phones :( 

Pixel 6 - Android 14

**Comment by msfjarvis** [comment] 2024-07-06 08:32
Duplicate of #3106, #2927, #2764, #2669, #2663, https://github.com/android-password-store/Android-Password-Store/issues/2644, https://github.com/android-password-store/Android-Password-Store/issues/2587, https://github.com/android-password-store/Android-Password-Store/issues/2553, https://github.com/android-password-store/Android-Password-Store/issues/2533 and https://github.com/android-password-store/Android-Password-Store/issues/2417.

**Closed as not planned by msfjarvis** 2024-07-06 08:32 UTC
Labels: S-invalid
