### ISSUE TITLE
[FEATURE] Add possibililty to work with multiple password stores

### ISSUE THREAD

**Issue by hcgrove** [zeapo/Android-Password-Store#2348] opened 2023-01-27 16:22 UTC
### Is your feature request related to a problem? Please describe.

I work with multiple (only two, but I see no reason why that would be a limit) password repos, using the linux program that is just a matter of having a couple of scripts that set some environment variables. I would like to be able to use them both/all on android.

### Describe the solution you'd like

Synchronise more than more git repo, when asked to synchronise. That should be simple enough.

Add a option to select a store when adding a password. That will add to the visual complexity when adding passwords, and in #1546 . that was (as I see it at least) the main reason for not implementing it right away. I could live with only being able to change this in the settings for the app.

### Describe alternatives you've considered

I unfortunately fail to see any alternatives.

**Comment by msfjarvis** [comment] 2023-01-27 16:23
Duplicate of #2302 and #260

**Closed as not planned by msfjarvis** 2023-01-27 16:23 UTC
Labels: C-feature, S-wontfix
