### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by githlp** [zeapo/Android-Password-Store#1222] opened 2020-11-28 21:52 UTC
**Is your feature request related to a problem? Please describe.**
Create new entry and when click on save the error message appears:

One key-id in .gpg-id is too short, please either use long key-ids (16 chars) or fingerprint (40 chars)

What am i now supposed to do with my gnupg sub-key ? Can i correct this somehow ?

The linux passwordstore application worked out fine but this was probably using the private key and not a sub-key..

**Describe the solution you'd like**
Maybe to work with short key-ids also ?

**Describe alternatives you've considered**
Red wine.

**Comment by msfjarvis** [comment] 2020-11-28 22:55
Duplicate of https://github.com/android-password-store/Android-Password-Store/issues/998, follow the guidance there.

**Closed as completed by msfjarvis** 2020-11-28 22:56 UTC

**Comment by githlp** [comment] 2020-11-29 07:11
Thanks a lot for quick directing to the solution.

Changing the keyid-format from short to long in .gpg-id worked out fine!
