### ISSUE TITLE
Importing SSH key doesn't work

### ISSUE THREAD

**Issue by emersion** [zeapo/Android-Password-Store#442] opened 2018-10-20 07:28 UTC
1. Start from scratch
2. Setup Git settings
3. Import SSH key with passphrase
4. The app says "SSH-key imported"
5. Clone repo
6. The app says "Unable to open the ssh-key, please check that it was imported"

The key has been generated with `ssh-keygen -t rsa -b 4096`.

**Comment by paualberto** [comment] 2018-12-11 14:14
Same here :/

**Comment by zidhuss** [comment] 2018-12-25 13:01
To help investigate, which app version that you had this issue on?

**Comment by emersion** [comment] 2018-12-25 13:02
Tried with 1.3.1.

**Comment by zidhuss** [comment] 2018-12-25 13:06
Cool, I'll see if I can find the cause of the issue.

**Comment by zidhuss** [comment] 2018-12-25 14:34
I've been able to reproduce the issue. After diving in I can see the JSch library is having trouble with the 4096 bit key that's generated.

We're getting a `JSchException` with the message `invalid private key` with the key that's generated.

**Comment by cgodfreyUW** [comment] 2019-01-02 03:06
Having the same issue using 2048 bit keys, FWIW.

**Comment by tomasz-oponowicz** [comment] 2019-01-02 09:42
> Having the same issue using 2048 bit keys, FWIW.

The same.

Command:

    sh-keygen -t rsa

Environment:
* openssh 7.9p1

**Comment by x1125** [comment] 2019-02-09 23:51
Does anyone know which type of keys are currently working?

**Comment by dwma** [comment] 2019-02-19 18:15
I've found out that if the key is generated with the '-m PEM' option (specifying the format), the app imports it successfully.

**Comment by paualberto** [comment] 2019-02-20 10:45
Can confirm that `ssh-keygen -m PEM` worked. :thinking:

**Comment by Integralist** [comment] 2019-04-25 11:45
I tried `ssh-keygen -f ~/.ssh/github_rsa -e -m pem` (from an existing ssh private key) and when attempting to import that to Password Store mobile app I still get the same error about being unable to open the ssh-key 🤔

**Comment by dimmie** [comment] 2019-05-07 18:55
I spent way too much time trying to get my FP2/F-Droid to effectively accept my SSH-Key.
Finally found this bug report and got an acceptable ssh key with :
$ ssh-keygen -t rsa -b 2048 -m PEM -f id_rsa_droid
I dispensed with a passphrase, but I guess it woudn't matter. MAYBE I will shout my frustration in the form of a donation ...

**Comment by dimmie** [comment] 2019-05-07 19:09
donation ... Arrrrgh - not bitcoin, not from me, I'd use PayPal any day, but bitcoin...
I'm tooo old-fashioned.

**Comment by unixispower** [comment] 2019-05-24 13:35
After fighting with my existing keys for a bit, I found [a promising serverfault answer](https://serverfault.com/a/950686) . It seems at some point OpenSSH changed the way private keys are stored. I am unsure if the key format difference in the new OpenSSH versions is to blame for this bug, but the command listed in the linked answer (`ssh-keygen -p -m PEM -f ~/.ssh/id_rsa`) generated a key I was able to import in the app.

Note: The command I included will overwrite the key in place; you might want to make a backup first.

**Comment by msfjarvis** [comment] 2019-09-14 08:01
unixispower's [answer](https://github.com/zeapo/Android-Password-Store/issues/442#issuecomment-495631214) resolves this issue on my reproducer, so I'm closing this. Documentation will be updated later to include this.

**Closed by msfjarvis** 2019-09-14 08:01 UTC
Labels: bug

**Comment by paualberto** [comment] 2019-09-14 09:57
It's not really a fix though, just a band-aid.
This app should be able to use all normal OpenSSH keys like pass and gopass. 😉

**Comment by jpellegrini** [comment] 2019-09-14 12:07
> It's not really a fix though, just a band-aid.
> This app should be able to use all normal OpenSSH keys like pass and gopass. wink

The fix did not work for me: I have tried creating an ed-25519 keypair with `ssh-keygen -t ed25519 -m PEM` , and it wasn't imported either.

**Comment by themightyoarfish** [comment] 2023-06-24 17:54
Ok so how does one use this with github.com?
The wiki says, one should generate an rsa key
```
ssh-keygen -t rsa -b 3072 -C "Android Password Store" -f /tmp/id_rsa_droid
```
however, this results in an error when cloning. The message is something like

> ERROR: You're using an RSA key with SHA-1, which is no longer allowed.

It's not quite clear to me if this is a message from the server, but I suspect so. The [github doc itself](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key) says one should generate an `ed25519` key.
Now when I do this and import the generated private key file, the app says "Imported" in the toast, but when cloning comes up with the same error in the OP. Same after applying the workaround posted earlier, which did work for an rsa key.

So 
- RSA -> converts and can be imported but won't work with github
- curve-> converts, but cannot be imported and maybe works with github

Has anyone had any success  with having a private repo on github.com?

For the record I used this app on an older android and did not have this problem there, though I may have set it up before github changed its stance on RSA keys.

**Comment by msfjarvis** [comment] 2023-06-24 18:01
Please use the [Discussions](https://github.com/android-password-store/Android-Password-Store/discussions) tab for questions and avoid commenting on old issues.

**Comment by Integralist** [comment] 2023-06-24 20:06
@themightyoarfish don't know if this helps (I use private GitHub repo) https://www.integralist.co.uk/posts/new-laptop-configuration/#password-store I discuss store setup and then the mobile app setup.
