### ISSUE TITLE
Nullpointer Exception while browsing passwords

### ISSUE THREAD

**Issue by oleastre** [zeapo/Android-Password-Store#198] opened 2016-07-19 13:26 UTC
My passwords are stored using the /website/username file scheme; and since commit 017650bf373e3ccc3a45680088297543a1470eff, when I click on one of the website (directory) name, password-store crashes with the following version.

Version 1.2.0.47 is working as expected.

```
java.lang.NullPointerException: Attempt to invoke interface method 'void com.zeapo.pwdstore.PasswordFragment$OnFragmentInteractionListener.onFragmentInteraction(com.zeapo.pwdstore.utils.PasswordItem)' on a null object reference
E/AndroidRuntime(28159):        at com.zeapo.pwdstore.utils.PasswordRecyclerAdapter$1.onClick(PasswordRecyclerAdapter.java:109)
E/AndroidRuntime(28159):        at android.view.View.performClick(View.java:4764)
E/AndroidRuntime(28159):        at android.view.View$PerformClick.run(View.java:19844)
E/AndroidRuntime(28159):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(28159):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(28159):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(28159):        at android.app.ActivityThread.main(ActivityThread.java:5349)
E/AndroidRuntime(28159):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28159):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(28159):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
E/AndroidRuntime(28159):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
```

**Comment by oleastre** [comment] 2016-07-19 13:26
Note, I'm using the version provided by f-droid.

**Comment by wongma7** [comment] 2016-07-19 14:07
Uh oh, I will reverse that change asap...

**Comment by jas4711** [comment] 2016-07-20 12:09
I can confirm this too -- thought it was a problem with my new ownCloud-based password store git repository, but reverting to 1.2.0.47 works fine.

**Comment by wongma7** [comment] 2016-07-22 01:16
This will be fixed in 1.2.0.50, when that comes out please confirm.

This happened because of a function getting deprecated and me not fully understanding what  that means :) + only testing the bare minimum on different Android versions. I'll be a lot more cautious about pushing out new versions from now on!

**Comment by Totktonada** [comment] 2016-07-22 23:11
Thanks all for helpful thread. I confirmed problem on 1.2.0.48 (it's last one in F-Droid) and confirmed problem disappered on after downgrading to 1.2.0.47. It would be better to update F-Droid's head asap to don't confuse users. Thanks again!

**Comment by wongma7** [comment] 2016-07-28 17:18
.51 out, somebody please try and confirm it's fixed

**Closed** 2016-07-28 17:27 UTC

**Comment by Totktonada** [comment] 2016-08-07 17:32
.52 works fine.
