### ISSUE TITLE
[FEATURE] multiple repos with configurable mount points

### ISSUE THREAD

**Issue by glowinthedark** [zeapo/Android-Password-Store#2302] opened 2022-12-17 12:39 UTC
The current implementation does not support more than one repository. This is a limitation that forces users to use another app or another client for a second password repository.

### Describe the solution you'd like

By default the app supports a single repository with an implicit logical mount point of root i.e. `/`. 

I.e.

```
+/<root>
    + example.com
        +account1
        + account2
    + example2.com
        + account3
        + account4
```

The proposed solution is to:

1. Add a mount point configuration parameter for the repo which will be prefilled with a default value eg `/` or `/somerepo`. Instead of `/` the mount point value can be taken from the last path segment of the repo, e.g. if the repo is `git@github.com:username/mysecretrepo.git` then the default pre-filled mount point can be `/mysecretrepo`.

This will result in the following hierarchy:

```
+/<root>
    + <mysecretrepo>
        + example.com
            +account1
            + account2
        + example2.com
            + account3
            + account4
    + <anotherrepo>
        + example3.com
            +account1
            + account2
        + example4.com
            + account1
            + account2
```

3. Enable configuring more than one storage backend (`git` or whatever other types will be supported in the future).
4. Validate that when adding another repository it is not pointing to the same mount point. (Collisions and validation errors can be reduced by pre-filling the repo name as the mount point.) 
5. Optionally, store the tree hierarchy location so that re-opening the app will show the previously selected sub-store (if more than one are configured).

### Describe alternatives you've considered

An alternative approach could be switching between multiple repos and only allow one repo to be active at one time. 

This has both advantages and disadvantages, as for example, users might not want to mix repositories and search in multiple repos. Also with the mount point approach the logic of the ➕ button might have to be reworked to make explicitly clear under which mount point a record is going to be created. This can be avoided by using the currently selected folder in the hierarchy although it might still lead to new items being created in another repo than the user intended. 

### Additional context

The idea of multiple stores is inspired by `gopass` https://github.com/gopasspw/gopass/blob/master/docs/features.md#features although their implementation is a bit cumbersome and unintuitive. Also, when more than one store is configured in `gopass` adding a new record adds an additional prompt for which store to use for saving the record. In the android version this can be avoided by using whatever store the user is currently located in, i.e. under which mount point the ➕ button was pressed.

**Comment by msfjarvis** [comment] 2022-12-17 12:57
Duplicate of #260

I have neither the interest nor the bandwidth for this feature (#1836)

**Closed as not planned** 2022-12-17 12:58 UTC
Labels: C-feature, S-wontfix
