### ISSUE TITLE
[AUTOFILL] Namecheap login form only presents generate password option

### ISSUE THREAD

**Issue by Quintasan** [zeapo/Android-Password-Store#971] opened 2020-07-26 12:19 UTC
I was trying to log in to namecheap.com and I do have a password for it in `Domains/namecheap.com` but Android Password Store only offers option to generate a password.

In the Settings I found option called Password file organisation which I set to `work/example.org` but that still doesn't make it work. I think this basically defeats the purpose of using pass which doesn't give a crap about how you store your passwords.

Can we get an option to search the password store in the menu which shows up when you start typing in an input field?

**Comment by msfjarvis** [comment] 2020-07-26 12:22
Please don't remove the bug report template when filing issues, we added it for a reason. There has always been an option to search passwords in the Autofill dialog as you can see in the attached screenshot.

<details>
<summary>Screenshot</summary>

![screenshot-20200726-175116](https://user-images.githubusercontent.com/13348378/88478780-a4674080-cf68-11ea-852b-58a5f8b4940d.png)


</details>

**Comment by Quintasan** [comment] 2020-07-26 12:35
Sorry about not using the issue template but I must have done something weird in the GH mobile  #application.


That's very weird but I am not getting that option in Firefox.

<details>
  <summary>Screenshot</summary>

![Screenshot_20200726-142632_Firefox](https://user-images.githubusercontent.com/6539261/88479067-0023d080-cf4d-11ea-8572-7d9666798d8d.png)

</details>

**Comment by fmeum** [comment] 2020-07-26 12:45
> Sorry about not using the issue template but I must have done something weird in the GH mobile  #application.
> 
> 
> That's very weird but I am not getting that option in Firefox.
> 

If you only see the "Generate password..." option it's because the website has declared that password field to be for a "new password" only (as opposed to a "current password"). 

You can still use the "Generate password..." option to enter and store any password you like though, and password store will fill both password fields on the namecheap sign up page with it.

**Comment by Quintasan** [comment] 2020-07-26 12:49
> > Sorry about not using the issue template but I must have done something weird in the GH mobile  #application.
> > 
> > 
> > That's very weird but I am not getting that option in Firefox.
> > 
> 
> If you only see the "Generate password..." option it's because the website has declared that password field to be for a "new password" only (as opposed to a "current password"). 
> 
> You can still use the "Generate password..." option to enter and store any password you like though, and password store will fill both password fields on the namecheap sign up page with it.

So this is a problem with Namecheap website in the end. Oh boy. Sorry for taking up your time.

**Comment by fmeum** [comment] 2020-07-26 12:52
> So this is a problem with Namecheap website in the end. Oh boy. Sorry for taking up your time.

Don't worry, we're still very much interested in reports like this. Could you provide me with a URL so that I can reproduce this issue with my own namecheap account?

**Comment by msfjarvis** [comment] 2020-07-26 12:53
> > So this is a problem with Namecheap website in the end. Oh boy. Sorry for taking up your time.
> 
> Don't worry, we're still very much interested in reports like this. Could you provide me with a URL so that I can reproduce this issue with my own namecheap account?

[This](https://www.namecheap.com/myaccount/login/?ReturnUrl=%2F%3F_ga%3D2.250223173.213913362.1595767281-2144648657.1595767281&_ga=2.250223173.213913362.1595767281-2144648657.1595767281) lets me repro.

**Comment by msfjarvis** [comment] 2020-07-26 12:54
Side note: seems to work correctly on Chrome Canary?

<details>
<summary>Screenshot</summary>

![screenshot-20200726-182430](https://user-images.githubusercontent.com/13348378/88479524-50128f80-cf6d-11ea-8ada-7114680f3eec.png)

</details>

**Comment by fmeum** [comment] 2020-07-26 12:57
> Side note: seems to work correctly on Chrome Canary?

That is to be expected: Chrome's Autofill support is more limited than Firefox's, so Password Store doesn't know whether a password field in Chrome is "new" or "current".

**Comment by msfjarvis** [comment] 2020-07-26 12:58
> > Side note: seems to work correctly on Chrome Canary?
> 
> That is to be expected: Chrome's Autofill support is more limited than Firefox's, so Password Store doesn't know whether a password field in Chrome is "new" or "current".

Well that's one benefit from Chrome Autofill being garbage...

**Comment by fmeum** [comment] 2020-07-26 12:59
> > > So this is a problem with Namecheap website in the end. Oh boy. Sorry for taking up your time.
> > 
> > Don't worry, we're still very much interested in reports like this. Could you provide me with a URL so that I can reproduce this issue with my own namecheap account?
> 
> [This](https://www.namecheap.com/myaccount/login/?ReturnUrl=%2F%3F_ga%3D2.250223173.213913362.1595767281-2144648657.1595767281&_ga=2.250223173.213913362.1595767281-2144648657.1595767281) lets me repro.

Let's label this a bug for now and I will take a deeper look.

**Comment by fmeum** [comment] 2020-07-27 07:56
This appears to be an accessibility bug in Firefox, maybe triggered by some specific weirdness in Namecheap's markup: The username field on the page is not represented by an accessibility node and focusing it generates error messages from `GeckoView` with Autofill not being triggered at all. 

The login page contains a hidden login form that is accessible via the "SIGN IN" dropdown menu in the upper left corner of the page. While Autofill should see one username and one password field for each of these forms and then select the one that is currently focused, due to the bug, it only sees one username field and two password fields that are all adjacent to each other (with respect to the order of input fields in the flattened HTML structure). But one username field and two consecutive password fields are recognized as a "new password" scenario.

In the end, I don't really know what to do about this, it's certainly tough to fix something that is caused by invalid input from the browser's side. @msfjarvis What do you think?

**Comment by msfjarvis** [comment] 2020-07-27 08:11
I personally don't think we should be working around this. Mozilla needs to be notified of this issue and if they unfortunately decide that things on their end are working "as intended", only then should we begin looking into workarounds on our side.

**Comment by fmeum** [comment] 2020-07-27 09:51
The bug is reproducible for me with the simplest possible markup recreating the Namecheap situation, so this is definitely not their fault:

```html
<!DOCTYPE html>
<html>
<body>
    <form>
        <input type="text" name="username_first" >
        <input type="password" name="password_first" >
        <input type="text" name="username_second" >
        <input type="password" name="password_second" >
    </form>
</body>
</html>
```

If I click the third input field, i.e., the second username field, I don't get any Autofill prompts with any Autofill app I tried. I will file a bug with Mozilla.

**Comment by fmeum** [comment] 2020-07-27 10:22
I filed the bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1655415
While researching this bug, I learned that Firefox now has limited but native Autofill support. It seems that the logic in [GeckoViewAutofill.jsm](https://searchfox.org/mozilla-central/source/mobile/android/modules/geckoview/GeckoViewAutofill.jsm) does some field detection on its own and can't handle more than one username field.

**Comment by msfjarvis** [comment] 2020-09-18 22:34
Still broken on Firefox Daylight build from today.

**Comment by msfjarvis** [comment] 2020-10-10 06:01
This isn't really our bug and Mozilla's not taking a lot of interest either so I'm going to go ahead and close this.

**Closed as completed by msfjarvis** 2020-10-10 06:01 UTC
