### ISSUE TITLE
[BUG] PGP key doesn't work in v2.0

### ISSUE THREAD

**Issue by cc8dea2e-4a29-4394-af6d-af0ccc73647a** [zeapo/Android-Password-Store#2846] opened 2024-01-04 09:36 UTC
### Describe the bug

Key added, app indicated the import was successful, but i cant use it - message saying that the passphrase is incorrect, when I try to view saved passwords.

### Steps to reproduce

1. Install apk from [latest release](https://github.com/android-password-store/Android-Password-Store/releases/download/latest/APS-freeRelease-2.0.0-SNAPSHOT.apk)
2. export gpg sub key from pc - `gpg --armor --export-secret-subkeys MySubKeyFingerprint! > subkey.asc`
3. Start app and clone pass repo 
4. Go to PGP setting and import sub key from step 2 (app indicated the import was successful)
5. Select a password from the store
6. Enter GPG passphrase in the password prompt
7. Click OK
8. App message - wrong password

### Expected behavior

Decrypt the password from store

### Device information

- Device: Lenovo Z5s
- OS: Android 11
- App version: v2.0

### Additional context

logs:
```
--------- beginning of main
01-04 10:52:36.955  4791  4791 I Zygote  : seccomp disabled by setenforce 0
01-04 10:52:36.967  4791  4791 E p.passwordstor: Not starting debugger since process cannot load the jdwp agent.
01-04 10:52:37.045  4791  4791 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-04 10:52:37.045  4791  4791 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-04 10:52:37.590  4791  4791 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
01-04 10:52:37.713  4791  4791 I Choreographer: Skipped 38 frames!  The application may be doing too much work on its main thread.
01-04 10:52:37.745  4791  7072 I AdrenoGLES: QUALCOMM build                   : ff079d7, I14b0d72ae8
01-04 10:52:37.745  4791  7072 I AdrenoGLES: Build Date                       : 10/22/19
01-04 10:52:37.745  4791  7072 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.02
01-04 10:52:37.745  4791  7072 I AdrenoGLES: Local Branch                     : 
01-04 10:52:37.745  4791  7072 I AdrenoGLES: Remote Branch                    : 
01-04 10:52:37.745  4791  7072 I AdrenoGLES: Remote Branch                    : 
01-04 10:52:37.745  4791  7072 I AdrenoGLES: Reconstruct Branch               : 
01-04 10:52:37.745  4791  7072 I AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
01-04 10:52:37.746  4791  4791 I RenderThread: type=1400 audit(0.0:4433): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=43798 scontext=u:r:untrusted_app:s0:c89,c257,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=1 app=app.passwordstore
01-04 10:52:37.751  4791  7072 I AdrenoGLES: PFP: 0x016ee187, ME: 0x00000000
01-04 10:52:37.787  4791  7072 I Gralloc4: mapper 4.x is not supported
01-04 10:52:37.789  4791  7072 W Gralloc3: mapper 3.x is not supported
01-04 10:52:37.806  4791  7072 I OpenGLRenderer: Davey! duration=738ms; Flags=1, IntendedVsync=12566744290974, Vsync=12567377624282, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=12567392675673, AnimationStart=12567392681507, PerformTraversalsStart=12567393210205, DrawStart=12567457745673, SyncQueued=12567458385100, SyncStart=12567461675413, IssueDrawCommandsStart=12567461783069, SwapBuffers=12567481440829, FrameCompleted=12567485696507, DequeueBufferDuration=2278490, QueueBufferDuration=3130937, GpuCompleted=0, 
01-04 10:52:41.433  4791  7072 D OpenGLRenderer: endAllActiveAnimators on 0x6fec985890 (MenuPopupWindow$MenuDropDownListView) with handle 0x6f0c958a30
01-04 10:52:43.312  4791  7087 D ProfileInstaller: Skipping profile installation for app.passwordstore
01-04 10:52:53.012  4791  7072 D OpenGLRenderer: endAllActiveAnimators on 0x6fec9e7600 (RippleDrawable) with handle 0x6f0c9743f0
01-04 10:53:04.592  4791  4791 W RecyclerView: No adapter attached; skipping layout
01-04 10:53:05.050  4791  4791 W RecyclerView: No adapter attached; skipping layout
01-04 10:53:15.374  4791  7072 D OpenGLRenderer: endAllActiveAnimators on 0x6feca5f510 (RippleDrawable) with handle 0x6f0c9835a0
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: NoKeysProvidedException
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(Unknown Source:529)
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository$decrypt$2.invokeSuspend(Unknown Source:38)
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: 	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:76)
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
01-04 10:53:15.403  4791  4791 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
01-04 10:53:15.568  4791  4791 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
01-04 10:53:15.576  4791  4791 W RecyclerView: No adapter attached; skipping layout
01-04 10:53:15.633  4791  4791 W RecyclerView: No adapter attached; skipping layout
01-04 10:53:29.730  4791  7072 D OpenGLRenderer: endAllActiveAnimators on 0x6feca6f7d0 (RippleDrawable) with handle 0x6f0c985df0
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: NoKeysProvidedException
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository.access$decryptPgp(Unknown Source:529)
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: 	at app.passwordstore.data.crypto.CryptoRepository$decrypt$2.invokeSuspend(Unknown Source:38)
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:114)
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: 	at androidx.core.app.ActivityRecreator$1.run(Unknown Source:76)
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
01-04 10:53:29.765  4791  4791 E StandaloneCoroutine: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:91)
01-04 10:53:29.931  4791  4791 W IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
01-04 10:53:29.936  4791  4791 W RecyclerView: No adapter attached; skipping layout
01-04 10:53:29.984  4791  4791 W RecyclerView: No adapter attached; skipping layout

```

**Comment by msfjarvis** [comment] 2024-01-04 09:58
That's more helpful, thanks. This is a dupe of https://github.com/android-password-store/Android-Password-Store/issues/2751, the app can't find a matching key because it doesn't understand the syntax.

**Closed as not planned by msfjarvis** 2024-01-04 09:58 UTC
Labels: C-bug, A-PGPainless, S-duplicate
