### ISSUE TITLE
[BUG] Keys are not listed

### ISSUE THREAD

**Issue by indeedwatson** [zeapo/Android-Password-Store#1065] opened 2020-08-28 01:07 UTC
I have a key in OpenKeychain, which I've allowed in the apps menu.

From password store I select clone from server, hidden, fill out my details, select openkeychain, hit clone, and a popup says to select a key, but there is nothing listed.

From the settings I have OpenKeychain as the pgp provider and i have the key ID selected (although it's not the name of the key, it says `0xc864`... it's a long number. If I hit that option again, the key shows up but it is unchecked (I don't know if this is the normal behavior, or an indication that the program is not remembering the selection).

In any case, regardless of that being set up, there is still nothing displayed when I need to add from the clone from server menu.

**Comment by msfjarvis** [comment] 2020-08-28 04:13
Please fill the issue template fully, it really makes things hard when you simply wipe it out :(

What version of the app are you on?

**Comment by indeedwatson** [comment] 2020-08-28 04:24
Sorry m8

**Expected behavior**
I expect the key to show up

**Device information (please complete the following information):**
 - Device: SM-A510M
 - OS: LineageOS 10
 - App version 5.5

**Additional context**
Add any other context about the problem here.

**Comment by msfjarvis** [comment] 2020-08-28 04:50
> Sorry m8
> 
> **Expected behavior**
> I expect the key to show up
> 
> **Device information (please complete the following information):**
>  - Device: SM-A510M
>  - OS: LineageOS 10
>  - App version 5.5
> 
> **Additional context**
> Add any other context about the problem here.
> 

Are you sure that's the version of the right app? Password Store has never left the 1.x.y versioning series.

**Comment by indeedwatson** [comment] 2020-08-28 04:51
1.9.2, I think I was looking at openkeychain sorry

**Comment by fmeum** [comment] 2020-08-28 06:12
> I have a key in OpenKeychain, which I've allowed in the apps menu.
> 
> From password store I select clone from server, hidden, fill out my details, select openkeychain, hit clone, and a popup says to select a key, but there is nothing listed.
> 
> From the settings I have OpenKeychain as the pgp provider and i have the key ID selected (although it's not the name of the key, it says `0xc864`... it's a long number. If I hit that option again, the key shows up but it is unchecked (I don't know if this is the normal behavior, or an indication that the program is not remembering the selection).
> 
> In any case, regardless of that being set up, there is still nothing displayed when I need to add from the clone from server menu.

It sounds to me like there is confusion about two different kind of keys: The key ID you select in settings is the for they key that encrypts the entries in your password store. But if you select OpenKeychain authentication in the Git server settings, OpenKeychain will ask you to select an authentication key. It is possible that you don't have one or at least haven't imported it into OpenKeychain. 

To check what kind of keys you have, select your key in OpenKeychain and open the `Advanced` view from the three-dot menu. The `Subkeys` tab will then provide you with the required information. If you are comfortable with it (e.g. because your GPG keys are public anyway), you could also share a screenshot here.

In more recent versions (current is 1.11.2, available from [here](https://github.com/android-password-store/Android-Password-Store/releases) or the Play Store), we have gotten rid of this explicit encryption key selection in favor of the contents of the `.gpg-id` in your repo, so please also give this a try and see whether it resolves the problem for you.

**Comment by indeedwatson** [comment] 2020-08-28 13:23
> To check what kind of keys you have, select your key in OpenKeychain and open the `Advanced` view from the three-dot menu. The `Subkeys` tab will then provide you with the required information. If you are comfortable with it (e.g. because your GPG keys are public anyway), you could also share a screenshot here.

There are two subkeys: one has a wax seal and a pen icon, and the other has a lock. If screenshot is necessary let me know and I'll see how to transfer it (KDEconnect is failing on me for some reason)


> In more recent versions (current is 1.11.2, available from [here](https://github.com/android-password-store/Android-Password-Store/releases) or the Play Store), we have gotten rid of this explicit encryption key selection in favor of the contents of the `.gpg-id` in your repo, so please also give this a try and see whether it resolves the problem for you.

I installed from F-Droid but I now see it says `Updated 1 month ago`, do you recommend against using F-Droid?

----

Installed 1.11.3 from Play store (through Aurora) and while the GUI seems improved, I have the same issue, no keys show up.

**Comment by fmeum** [comment] 2020-08-28 14:14
> There are two subkeys: one has a wax seal and a pen icon, and the other has a lock. If screenshot is necessary let me know and I'll see how to transfer it (KDEconnect is failing on me for some reason)

Thanks for the info, that helps: The wax seal means that the first key is your master key with which you can sign other keys. The pen icon says that your master key can also be used to sign arbitrary messages. The key with the lock icon is your encryption key. However, you would need another subkey, an authentication key, to perform SSH authentication via OpenKeychain. Such a subkey would have an ID card symbol. You can probably create one within OpenKeychain or import it from a computer.

I will close the issue since this is very likely the cause of the issue.


> I installed from F-Droid but I now see it says `Updated 1 month ago`, do you recommend against using F-Droid?

There is nothing wrong with F-Droid in general. However, @msfjarvis and I tend to be early adopters of new Android dev tools and libraries, which sometimes causes build issues if F-Droid hasn't roled out support for a certain build-related feature yet. So just keep in mind that F-Droid will not necessarily be updated at the same time as our other release channels.

**Closed as completed by fmeum** 2020-08-28 14:14 UTC

**Comment by indeedwatson** [comment] 2020-08-28 17:05
@FabianHenneke alright thanks, I'll see about the key. Tbh it's pretty confusing, I haven't found this explained in detail anywhere.

**Comment by msfjarvis** [comment] 2020-08-28 18:45
> Tbh it's pretty confusing, I haven't found this explained in detail anywhere.

That's true, our documentation is sorely lacking and while there's been community interest in having them, there is not much in the way of volunteering to provide it. There's a _lot_ of ground to cover here and its just very hard to balance that and the daily maintenance so we add on to the documentation as and when issues arise.

**Comment by indeedwatson** [comment] 2020-08-31 23:51
I ended up generating a key from Open Keychain, same issue, the icon you mentioned @FabianHenneke is not there either, and the key doesn't show up. How should I proceed?

**Comment by fmeum** [comment] 2020-09-01 05:11
> I ended up generating a key from Open Keychain, same issue, the icon you mentioned @FabianHenneke is not there either, and the key doesn't show up. How should I proceed?

Indeed, for some reason OpenKeychain doesn't create authentication subkeys by default. You can add one as follows while generating a new key, generating just a new subkey should work similarly:
![Screenshot_20200901-070913.png](https://user-images.githubusercontent.com/4312191/91797189-46421300-ec22-11ea-89f7-f442297e80b7.png)
![Screenshot_20200901-070923.png](https://user-images.githubusercontent.com/4312191/91797199-48a46d00-ec22-11ea-80bd-46b0e67b6ad0.png)
![Screenshot_20200901-070931.png](https://user-images.githubusercontent.com/4312191/91797224-53f79880-ec22-11ea-82fd-ded49439ed5a.png)
![Screenshot_20200901-070940.png](https://user-images.githubusercontent.com/4312191/91797230-5823b600-ec22-11ea-8e41-111ccadfdf55.png)
