### ISSUE TITLE
[BUG] Autofill only opens after closing and reopening Chrome

### ISSUE THREAD

**Issue by Airblader** [zeapo/Android-Password-Store#1714] opened 2022-02-05 17:08 UTC
### Describe the bug

When I navigate to some website with a login in Chrome and tap on the fields, the APS autofill menu doesn't show up. However, if I go to the home screen (with that box focused) and open Chrome back up, the menu does show up.

### Steps to reproduce

1. Go to any website with a login.
2. Click on the name or password field.
3. No autofill shows up.
4. Go to home screen.
5. Go back to Chrome.
6. Autofill now shows up.

### Expected behavior

Autofill should show immediately.

### Device information

- Device: Samsung Galaxy S21 Ultra
- OS: Android 12 with One UI 4
- App version 1.13.5

### Additional context

I tried disabling autofill and going through the setup to enable it again without luck.

Thanks so much for your work on this app!

**Comment by fmeum** [comment] 2022-02-05 17:25
Could you provide us with your Chrome version and a URL with a form with which you can reproduce the issue?

**Comment by Airblader** [comment] 2022-02-05 17:28
Thanks for the swift answer, and sorry for not providing the Chrome version right away: 90.8.4758.87.

Some random example where I can reproduce it: 
https://semantic-ui.com/examples/login.html

**Comment by msfjarvis** [comment] 2022-02-05 17:34
> Thanks for the swift answer, and sorry for not providing the Chrome version right away: 90.8.4758.87.
> 
> Some random example where I can reproduce it: [semantic-ui.com/examples/login.html](https://semantic-ui.com/examples/login.html)

I can't reproduce the issue on this page using Chrome 97. Can you try a more recent version of Chrome? The 90.x release train is over a year old.

**Comment by Airblader** [comment] 2022-02-05 17:41
Sorry, there was a number mixup in the version (curse you Chrome for not making it copy-paste able). It's 98.0.4758.87, latest in Play Store for me.

**Comment by Airblader** [comment] 2022-02-05 17:51
I just installed Chrome Beta (99.x) from the Play Store and there it seems to work just fine. Maybe an issue with Chrome 98.x?

**Comment by fmeum** [comment] 2022-02-05 18:16
I have been able to repro the issue once on 98, but not on 99.

We could leave this issue open until 99 has been released in case other users run into it.

**Comment by Airblader** [comment] 2022-02-05 18:27
Makes sense. Thanks for looking into it!

**Comment by msfjarvis** [comment] 2022-03-10 20:39
Chrome 99 hit stable 10 days ago: https://chromestatus.com/roadmap

**Closed as completed by msfjarvis** 2022-03-10 20:39 UTC
Labels: C-bug, A-autofill, S-unactionable, S-help-wanted
