### ISSUE TITLE
weird behavior with custom ssh port

### ISSUE THREAD

**Issue by Lompik** [zeapo/Android-Password-Store#89] opened 2015-06-04 04:41 UTC
First with current release downloaded from play store: 

- setup ssh method to clone (bare) repo as : `username@192.168.100.99:33451/tmp/pwd` + setup ssh key. 
- the app is able to clone the repo
- However with push/pull nothing happend (no network packet are seen through `tcpdump`). COnnections times out (with correct port number in error message)
- while editing the git Settings, I am unable to save. Nothing happens when save button pushed. Forced to use arrow back.
- Trying to edit again the git settings: custom port is now defaulted to 22 (!). Note that I have not edited in the previous step. Nonetheless I set it back to 33451. Unable to hit `save` button so hit back arrow. When trying to push/pull, the connection is reset as the app use port 22 but displays the address `username@192.168.100.99:33451/tmp/pwd`

Secondly with the  	`v1.2.0.19 apk` release from github:

- unable to set a custom port as the app crashed when I hit save button.

Is anything wrong with my Phone ?

**Comment by bulldozer2003** [comment] 2015-06-04 15:16
+1 I have these problems with version 1.2.0.17 from F-Droid
*Save button does not do anything
*Custom port is not saved, reverts to 22
*Same error message when trying to sync, push, or pull

**Comment by zeapo** [comment] 2015-06-04 17:25
Thanks for the report. Can you confirm whether 1.2.0.15 works or not?

**Comment by Lompik** [comment] 2015-06-04 22:19
with `1.2.0.15` the first time you clone the repo, Push and Pull works. Howerver the UI issue with the git setting still persist.

**Comment by zeapo** [comment] 2015-06-04 22:25
thanks

Le ven. 5 juin 2015 à 00:19, James Browder <notifications@github.com> a
écrit :

**Comment by zeapo** [comment] 2015-06-07 12:35
@Lompik I am unable to reproduce your git issue, here is a test with a clean vagrant image and a cleared data install of the app http://media.giphy.com/media/l41lIxjibYQ9kqkP6/giphy.gif

- The port bug has been fixed in dd5c396b0dd39cc4a4a45fcc81a2b757c8088e37

**Comment by Lompik** [comment] 2015-06-08 19:38
I just tested the new build (.20) and I think setting the port in the UI works as expected. I was able to pull. However when trying to push, here's the small quirks: ports seem to be configured fine but it not used by jgit (which still use 22):

![screenshot_2015-06-08-14-29-52](https://cloud.githubusercontent.com/assets/3791334/8043455/f5fea1ac-0deb-11e5-90eb-09a3cb94f683.png)

**Comment by zeapo** [comment] 2015-06-08 21:28
If I understand well, you specified a custom port and when trying to push, it used port 22?

If it's the case, could you clear data and retry?

**Comment by Lompik** [comment] 2015-06-08 23:51
yes you understand correctly. Sorry for not being clear.

if by clear data you mean delete repository from settings,  pull & push then yes the app was able to push. The `diff log` on the server looked like : 
    
    [ANDROID PwdStore] Addtestfrom store

Maybe we could add some spaces in before and after item `test` ? 

On my phone when entering a new item, if the screen get rotated, all the user input is removed. No sure if that is a feature or not.

**Comment by zeapo** [comment] 2015-06-12 20:27
seems like all is alright for v.21. I will create a new issue for the screen rotation.

Please reopen the issue if you encounter the same problems once again.

**Closed by zeapo** 2015-06-12 20:27 UTC
Labels: bug

**Comment by bulldozer2003** [comment] 2015-06-12 20:36
Thanks @zeapo 

Can you push an update to F-Droid soon?

**Comment by zeapo** [comment] 2015-06-12 20:57
I just tagged it. It should be available tomorrow (it's an automatic build)

Le ven. 12 juin 2015 à 22:36, bulldozer2003 <notifications@github.com> a
écrit :
