### ISSUE TITLE
[BUG] "Socket closed" on first repository clone

### ISSUE THREAD

**Issue by blastrock** [zeapo/Android-Password-Store#1143] opened 2020-10-08 19:45 UTC
**Describe the bug**
I'm trying to clone my git repository through ssh, and I get a dialog box saying "An error occurred during a Git operation" and "Socket closed"

**To Reproduce**
1. Start password manager
2. Generate a key (tried RSA and ECDSA) and add it to your server
3. Fill in the host address
4. Clone the repository

**Expected behavior**
Success

**Device information:**
 - Device: Oneplus 3T
 - OS: Lineage 16 (Android 9)
 - App version 1.12.0

**Additional context**
Couldn't find anything in logcat. On my server I get:

    Oct 08 21:40:06 axanux sshd[390715]: Connection closed by authenticating user blastrock 192.168.0.105 port 44383 [preauth]

**Comment by msfjarvis** [comment] 2020-10-09 05:10
You can go into settings from the main screen and enable debug logging. Then force stopping and re-launching will start populating logcat. I can't reproduce this on any of my servers and I don't particularly think this is a client bug so a confirmation via logcat would be helpful.

**Comment by blastrock** [comment] 2020-10-11 10:06
With the debug logging enabled, here's the logcat snippet:

```
10-11 11:58:33.898 24120 24140 D SshTransport: Pinned host key: SHA256:grSHEdHMJEXHMetk2yLQjLTBYREUtWiWOIclHvphgd4=
10-11 11:58:33.999 24120 24140 I net.schmizz.sshj.transport.TransportImpl: Client identity string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
10-11 11:58:34.026 24120 24140 I net.schmizz.sshj.transport.TransportImpl: Server identity string: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1
10-11 11:58:34.027 24120 24140 D net.schmizz.concurrent.Promise: Setting <<kex done>> to `null`
10-11 11:58:34.027 24120 24140 D net.schmizz.sshj.transport.KeyExchanger: Sending SSH_MSG_KEXINIT
10-11 11:58:34.030 24120 24166 V net.schmizz.sshj.transport.Decoder: Received packet #0: 14 86 a1 81 a8 2f 9a 14 b5 9d b9 af 79 20 f0 7d bc 00 00 00 e6 63 75 72 76 65 32 35 35 31 39 2d 73 68 61 32 35 36 2c 63 75 72 76 65 32 35 35 31 39 2d 73 68 61 32 35 36 40 6c 69 62 73 73 68 2e 6f 72 67 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 33 38 34 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 35 32 31 2c 64 69 66 66 69 65 2d 68 65 6c 6c 6d 61 6e 2d 67 72 6f 75 70 2d 65 78 63 68 61 6e 67 65 2d 73 68 61 32 35 36 2c 64 69 66 66 69 65 2d 68 65 6c 6c 6d 61 6e 2d 67 72 6f 75 70 31 36 2d 73 68 61 35 31 32 2c 64 69 66 66 69 65 2d 68 65 6c 6c 6d 61 6e 2d 67 72 6f 75 70 31 38 2d 73 68 61 35 31 32 2c 64 69 66 66 69 65 2d 68 65 6c 6c 6d 61 6e 2d 67 72 6f 75 70 31 34 2d 73 68 61 32 35 36 00 00 00 41 72 73 61 2d 73 68 61 32 2d 35 31 32 2c 72 73 61 2d 73 68 61 32 2d 32 35 36 2c 73 73 68 2d 72 73 61 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 2c 73 73 68 2d 65 64 32 35 35 31 39 00 00 00 6c 63 68 61 63 68 61 32 30 2d 70 6f 6c 79 31 33 30 35 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 61 65 73 31 32 38 2d 63 74 72 2c 61 65 73 31 39 32 2d 63 74 72 2c 61 65 73 32 35 36 2d 63 74 72 2c 61 65 73 31 32 38 2d 67 63 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 61 65 73 32 35 36 2d 67 63 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 00 00 00 6c 63 68 61 63 68 61 32 30 2d 70 6f 6c 79 31 33 30 35 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 61 65 73 31 32 38 2d 63 74 72 2c 61 65 73 31 39 32 2d 63 74 72 2c 61 65 73 32 35 36 2d 63 74 72 2c 61 65 73 31 32 38 2d 67 63 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 61 65 73 32 35 36 2d 67 63 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 00 00 00 d5 75 6d 61 63 2d 36 34 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 75 6d 61 63 2d 31 32 38 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 31 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 75 6d 61 63 2d 36 34 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 75 6d 61 63 2d 31 32 38 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 2c 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2c 68 6d 61 63 2d 73 68 61 31 00 00 00 d5 75 6d 61 63 2d 36 34 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 75 6d 61 63 2d 31 32 38 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 31 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 75 6d 61 63 2d 36 34 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 75 6d 61 63 2d 31 32 38 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 2c 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2c 68 6d 61 63 2d 73 68 61 31 00 00 00 15 6e 6f 6e 65 2c 7a 6c 69 62 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 00 00 00 15 6e 6f 6e 65 2c 7a 6c 69 62 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 00 00 00 00 00 00 00 00 00 00 00 00 00
10-11 11:58:34.031 24120 24166 V net.schmizz.sshj.transport.TransportImpl: Received packet KEXINIT
10-11 11:58:34.031 24120 24166 D net.schmizz.sshj.transport.KeyExchanger: Received SSH_MSG_KEXINIT
10-11 11:58:34.031 24120 24166 D net.schmizz.concurrent.Promise: Awaiting <<kexinit sent>>
10-11 11:58:34.036 24120 24140 V net.schmizz.sshj.transport.Encoder: Encoding packet #0: 14 62 b3 a3 ab e6 40 e3 2b f9 ea 5f 14 32 f0 f4 50 00 00 00 97 63 75 72 76 65 32 35 35 31 39 2d 73 68 61 32 35 36 2c 63 75 72 76 65 32 35 35 31 39 2d 73 68 61 32 35 36 40 6c 69 62 73 73 68 2e 6f 72 67 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 35 32 31 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 33 38 34 2c 65 63 64 68 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 2c 64 69 66 66 69 65 2d 68 65 6c 6c 6d 61 6e 2d 67 72 6f 75 70 2d 65 78 63 68 61 6e 67 65 2d 73 68 61 32 35 36 2c 65 78 74 2d 69 6e 66 6f 2d 63 00 00 00 86 73 73 68 2d 72 73 61 2d 63 65 72 74 2d 76 30 31 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 73 73 68 2d 65 64 32 35 35 31 39 2c 72 73 61 2d 73 68 61 32 2d 35 31 32 2c 72 73 61 2d 73 68 61 32 2d 32 35 36 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 35 32 31 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 33 38 34 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 2c 73 73 68 2d 72 73 61 00 00 00 20 61 65 73 32 35 36 2d 63 74 72 2c 61 65 73 31 39 32 2d 63 74 72 2c 61 65 73 31 32 38 2d 63 74 72 00 00 00 20 61 65 73 32 35 36 2d 63 74 72 2c 61 65 73 31 39 32 2d 63 74 72 2c 61 65 73 31 32 38 2d 63 74 72 00 00 00 57 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 00 00 00 57 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 2d 65 74 6d 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 68 6d 61 63 2d 73 68 61 32 2d 35 31 32 2c 68 6d 61 63 2d 73 68 61 32 2d 32 35 36 00 00 00 04 6e 6f 6e 65 00 00 00 04 6e 6f 6e 65 00 00 00 00 00 00 00 00 00 00 00 00 00
10-11 11:58:34.036 24120 24140 D net.schmizz.concurrent.Promise: Setting <<kexinit sent>> to `SOME`
10-11 11:58:34.037 24120 24140 D net.schmizz.concurrent.Promise: Awaiting <<kex done>>
10-11 11:58:34.038 24120 24166 D net.schmizz.sshj.transport.KeyExchanger: Negotiated algorithms: [ kex=curve25519-sha256; sig=ssh-ed25519; c2sCipher=aes256-ctr; s2cCipher=aes256-ctr; c2sMAC=hmac-sha2-512-etm@openssh.com; s2cMAC=hmac-sha2-512-etm@openssh.com; c2sComp=none; s2cComp=none; rsaSHA2Support=true ]
10-11 11:58:34.117 24120 24166 V net.schmizz.sshj.transport.Encoder: Encoding packet #1: 1e 00 00 00 20 fb e0 87 a6 3c 70 4c 11 53 71 53 a7 c5 57 ec 21 25 b9 d0 eb 64 6a 0d d6 c5 0d 21 9d f0 cd b6 7a
10-11 11:58:34.141 24120 24166 V net.schmizz.sshj.transport.Decoder: Received packet #1: 1f 00 00 00 33 00 00 00 0b 73 73 68 2d 65 64 32 35 35 31 39 00 00 00 20 60 8e bf 0b 89 ab 41 d6 66 90 da 35 f5 3d 7f 61 9b 70 ad 7a 18 c3 f7 7f 25 2d f6 aa f1 7a 1a 6b 00 00 00 20 dd f9 94 3e cf b0 fb 07 97 25 60 e5 6e fb 2c c7 3d be 33 b1 ee 12 4e 50 d5 72 af 3c 49 36 22 14 00 00 00 53 00 00 00 0b 73 73 68 2d 65 64 32 35 35 31 39 00 00 00 40 59 61 fe 37 e7 42 95 cf 0d 27 a9 08 3a 69 8b 73 47 03 34 a3 7a d4 6c 63 9e 86 e1 66 78 ca bf 6a 0d 4c dc 91 de c2 7c 9c 15 9c b5 4d 04 bc 4a 6b a8 6a b6 d0 72 56 7b 59 c6 98 bf a6 1a 18 b1 09
10-11 11:58:34.141 24120 24166 V net.schmizz.sshj.transport.TransportImpl: Received packet KEXDH_31
10-11 11:58:34.141 24120 24166 D net.schmizz.sshj.transport.KeyExchanger: Received kex followup data
10-11 11:58:34.171  2094  2338 E fpc_fingerprint_hal: fpc_wait_finger_up FPC_LIB_FINGER_LOST
10-11 11:58:34.171  2094  2338 E fpc_fingerprint_hal: do_home fpc_wait_finger_up before do HOME ,status 0 
10-11 11:58:34.171  2094  2338 D fpc_fingerprint_hal: fpc_wait_finger_down_for_home_12_zone enter
10-11 11:58:34.171  2094  2338 D fpc_tac : fpc_tac_12zones_wakeup_setup begin
10-11 11:58:34.171  2094  2338 D fpc_tac : fpc_tac_send_cmd begin
10-11 11:58:34.178  2094  2338 D fpc_tac : fpc_tac_send_cmd end
10-11 11:58:34.178  2094  2338 D fpc_tac : fpc_tac_12zones_wakeup_setup end
10-11 11:58:34.248   569   608 W SurfaceFlinger: Attempting to destroy on removed layer: 2b0cc12 FingerprintDialogView#0
10-11 11:58:34.282 24120 24166 D net.schmizz.sshj.transport.KeyExchanger: Trying to verify host key with FingerprintVerifier{digestAlgorithm='SHA-256'}
10-11 11:58:34.283 24120 24166 D net.schmizz.sshj.transport.KeyExchanger: Sending SSH_MSG_NEWKEYS
10-11 11:58:34.283 24120 24166 V net.schmizz.sshj.transport.Encoder: Encoding packet #2: 15
10-11 11:58:34.284 24120 24166 V net.schmizz.sshj.transport.Decoder: Received packet #2: 15
10-11 11:58:34.284 24120 24166 V net.schmizz.sshj.transport.TransportImpl: Received packet NEWKEYS
10-11 11:58:34.284 24120 24166 D net.schmizz.sshj.transport.KeyExchanger: Received SSH_MSG_NEWKEYS
10-11 11:58:34.286 24120 24166 D net.schmizz.concurrent.Promise: Setting <<kexinit sent>> to `null`
10-11 11:58:34.286 24120 24166 D net.schmizz.concurrent.Promise: Setting <<kex done>> to `SOME`
10-11 11:58:34.287 24120 24140 D net.schmizz.sshj.SSHClient: Key exchange took 0.261 seconds
10-11 11:58:34.287 24120 24166 V net.schmizz.sshj.transport.Decoder: Received packet #3: 07 00 00 00 01 00 00 00 0f 73 65 72 76 65 72 2d 73 69 67 2d 61 6c 67 73 00 00 00 af 73 73 68 2d 65 64 32 35 35 31 39 2c 73 6b 2d 73 73 68 2d 65 64 32 35 35 31 39 40 6f 70 65 6e 73 73 68 2e 63 6f 6d 2c 73 73 68 2d 72 73 61 2c 72 73 61 2d 73 68 61 32 2d 32 35 36 2c 72 73 61 2d 73 68 61 32 2d 35 31 32 2c 73 73 68 2d 64 73 73 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 33 38 34 2c 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 35 32 31 2c 73 6b 2d 65 63 64 73 61 2d 73 68 61 32 2d 6e 69 73 74 70 32 35 36 40 6f 70 65 6e 73 73 68 2e 63 6f 6d
10-11 11:58:34.287 24120 24166 V net.schmizz.sshj.transport.TransportImpl: Received packet EXT_INFO
10-11 11:58:34.287 24120 24166 D net.schmizz.sshj.transport.TransportImpl: Received SSH_MSG_EXT_INFO
10-11 11:58:34.289 24120 24140 D net.schmizz.concurrent.Promise: Setting <<service accept>> to `null`
10-11 11:58:34.290 24120 24140 D net.schmizz.sshj.transport.TransportImpl: Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth
10-11 11:58:34.290 24120 24140 V net.schmizz.sshj.transport.Encoder: Encoding packet #3: 05 00 00 00 0c 73 73 68 2d 75 73 65 72 61 75 74 68
10-11 11:58:34.291 24120 24140 D net.schmizz.concurrent.Promise: Awaiting <<service accept>>
10-11 11:58:34.292 24120 24166 V net.schmizz.sshj.transport.Decoder: Received packet #4: 06 00 00 00 0c 73 73 68 2d 75 73 65 72 61 75 74 68
10-11 11:58:34.292 24120 24166 V net.schmizz.sshj.transport.TransportImpl: Received packet SERVICE_ACCEPT
10-11 11:58:34.292 24120 24166 D net.schmizz.sshj.transport.TransportImpl: Setting active service to ssh-userauth
10-11 11:58:34.293 24120 24166 D net.schmizz.concurrent.Promise: Setting <<service accept>> to `SOME`
10-11 11:58:34.293 24120 24140 D net.schmizz.concurrent.Promise: Setting <<authenticated>> to `null`
10-11 11:58:34.294 24120 24140 D net.schmizz.sshj.userauth.UserAuthImpl: Trying `publickey` auth...
10-11 11:58:34.294 24120 24140 D net.schmizz.sshj.userauth.method.AuthPublickey: Attempting authentication using com.zeapo.pwdstore.git.sshj.SshKey$KeystoreNativeKeyProvider@9c2181
10-11 11:58:34.300 24120 24140 V net.schmizz.sshj.transport.Encoder: Encoding packet #4: 32 00 00 00 09 62 6c 61 73 74 72 6f 63 6b 00 00 00 0e 73 73 68 2d 63 6f 6e 6e 65 63 74 69 6f 6e 00 00 00 09 70 75 62 6c 69 63 6b 65 79 00 00 00 00 0c 72 73 61 2d 73 68 61 32 2d 35 31 32 00 00 01 97 00 00 00 07 73 73 68 2d 72 73 61 00 00 00 03 01 00 01 00 00 01 81 00 c1 c5 d6 8b a2 91 0c 04 82 c0 99 a5 62 b8 78 86 85 d0 47 7d 12 2b 72 68 04 68 7c de 34 fe 32 07 a5 ac a9 26 73 b1 59 6e 7e 0b 60 90 0b e3 c2 bd 24 f0 63 60 37 a3 f6 7c 61 fc 44 f5 bf 79 07 b3 f3 6e 3e 05 22 80 6a 6f 34 d5 34 37 7e ec 14 32 eb 61 aa 48 3e f2 32 df e8 a7 81 bf 4f 61 c8 6f 8a 00 a9 c0 25 65 8f 88 8c 1a fd f3 11 86 47 fd 2e 47 ac 31 28 92 f6 14 b5 89 db 6e 02 f9 11 f9 6c 53 e2 f3 d9 ed ea c8 0c 84 d7 27 5d 9d 50 66 ea 02 48 5c 9b 82 bc 96 93 ec 02 ff 38 bd e0 de 80 0e 7f bb 5c dc bc 51 6c a9 ed fa 45 dc 8a ed a2 fd 43 2f e8 ce 0e 26 50 34 11 9a 4e 1f 69 3a 8d 07 2e 77 00 3a b0 e7 3f e2 bd b8 e2 68 54 7b 04 6b 76 9e e6 df d0 ee 9e 01 da 77 80 1c d8 a2 f2 79 be e7 6b 84 9d 91 45 30 8b 85 62 73 0e 92 f7 f2 8d 0f b8 77 42 d3 d6 29 43 61 09 07 fb 91 a4 0b 7f b6 1a 5f 26 d1 00 f4 ae 6d 81 eb dc c3 cb ed 33 03 b8 a2 89 ac 7e 08 a2 22 ca 2f d7 33 22 64 03 ce 78 2e 0c ea cd 7f 9a d1 12 4c f0 80 b9 46 8f 71 6b 8a 63 7b 8e 8b 57 8f 7f b7 70 40 d5 ac e9 9c cf 4e 19 5c 91 2a 49 b0 77 3a 04 5a 71 8c 1d df 1e f4 4a 67 b2 e6 2a db 68 27 53 19 d8 77 f3 05 7c 01 46 3a 3f 3e 36 7b ad b8 fa ff ec 18 c1 a9 7b d4 89 4a ae ae f1 4c 3e a4 d8 1b
10-11 11:58:34.300 24120 24140 D net.schmizz.concurrent.Promise: Awaiting <<authenticated>>
10-11 11:58:34.308 24120 24166 V net.schmizz.sshj.transport.Decoder: Received packet #5: 3c 00 00 00 0c 72 73 61 2d 73 68 61 32 2d 35 31 32 00 00 01 97 00 00 00 07 73 73 68 2d 72 73 61 00 00 00 03 01 00 01 00 00 01 81 00 c1 c5 d6 8b a2 91 0c 04 82 c0 99 a5 62 b8 78 86 85 d0 47 7d 12 2b 72 68 04 68 7c de 34 fe 32 07 a5 ac a9 26 73 b1 59 6e 7e 0b 60 90 0b e3 c2 bd 24 f0 63 60 37 a3 f6 7c 61 fc 44 f5 bf 79 07 b3 f3 6e 3e 05 22 80 6a 6f 34 d5 34 37 7e ec 14 32 eb 61 aa 48 3e f2 32 df e8 a7 81 bf 4f 61 c8 6f 8a 00 a9 c0 25 65 8f 88 8c 1a fd f3 11 86 47 fd 2e 47 ac 31 28 92 f6 14 b5 89 db 6e 02 f9 11 f9 6c 53 e2 f3 d9 ed ea c8 0c 84 d7 27 5d 9d 50 66 ea 02 48 5c 9b 82 bc 96 93 ec 02 ff 38 bd e0 de 80 0e 7f bb 5c dc bc 51 6c a9 ed fa 45 dc 8a ed a2 fd 43 2f e8 ce 0e 26 50 34 11 9a 4e 1f 69 3a 8d 07 2e 77 00 3a b0 e7 3f e2 bd b8 e2 68 54 7b 04 6b 76 9e e6 df d0 ee 9e 01 da 77 80 1c d8 a2 f2 79 be e7 6b 84 9d 91 45 30 8b 85 62 73 0e 92 f7 f2 8d 0f b8 77 42 d3 d6 29 43 61 09 07 fb 91 a4 0b 7f b6 1a 5f 26 d1 00 f4 ae 6d 81 eb dc c3 cb ed 33 03 b8 a2 89 ac 7e 08 a2 22 ca 2f d7 33 22 64 03 ce 78 2e 0c ea cd 7f 9a d1 12 4c f0 80 b9 46 8f 71 6b 8a 63 7b 8e 8b 57 8f 7f b7 70 40 d5 ac e9 9c cf 4e 19 5c 91 2a 49 b0 77 3a 04 5a 71 8c 1d df 1e f4 4a 67 b2 e6 2a db 68 27 53 19 d8 77 f3 05 7c 01 46 3a 3f 3e 36 7b ad b8 fa ff ec 18 c1 a9 7b d4 89 4a ae ae f1 4c 3e a4 d8 1b
10-11 11:58:34.308 24120 24166 V net.schmizz.sshj.transport.TransportImpl: Received packet USERAUTH_60
10-11 11:58:34.308 24120 24166 D net.schmizz.sshj.userauth.UserAuthImpl: Asking `publickey` method to handle USERAUTH_60 packet
10-11 11:58:34.308 24120 24166 D net.schmizz.sshj.userauth.method.AuthPublickey: Key acceptable, sending signed request
10-11 11:58:34.309 24120 24166 D net.schmizz.sshj.userauth.method.AuthPublickey: Attempting authentication using com.zeapo.pwdstore.git.sshj.SshKey$KeystoreNativeKeyProvider@9c2181
10-11 11:58:34.346  1977  1977 E keystore: getAuthToken failed: -2
10-11 11:58:34.360 24120 24166 E net.schmizz.sshj.transport.TransportImpl: Dying because - User not authenticated
10-11 11:58:34.361 24120 24166 I net.schmizz.sshj.transport.TransportImpl: Disconnected - UNKNOWN
10-11 11:58:34.361 24120 24166 D net.schmizz.sshj.transport.KeyExchanger: Got notified of net.schmizz.sshj.common.SSHException: User not authenticated
10-11 11:58:34.361 24120 24166 D net.schmizz.sshj.userauth.UserAuthImpl: Notified of net.schmizz.sshj.common.SSHException: User not authenticated
10-11 11:58:34.362 24120 24166 D net.schmizz.sshj.transport.TransportImpl: Setting active service to null-service
10-11 11:58:34.362 24120 24140 E net.schmizz.concurrent.Promise: <<authenticated>> woke to: net.schmizz.sshj.userauth.UserAuthException: User not authenticated
10-11 11:58:34.362 24120 24140 D net.schmizz.concurrent.Promise: Setting <<service accept>> to `null`
10-11 11:58:34.362 24120 24140 D net.schmizz.sshj.transport.TransportImpl: Sending SSH_MSG_SERVICE_REQUEST for ssh-userauth
10-11 11:58:34.362 24120 24140 V net.schmizz.sshj.transport.Encoder: Encoding packet #5: 05 00 00 00 0c 73 73 68 2d 75 73 65 72 61 75 74 68
10-11 11:58:34.363 24120 24166 D net.schmizz.concurrent.Promise: Setting <<transport close>> to `SOME`
10-11 11:58:34.363 24120 24166 D net.schmizz.sshj.transport.Reader: Stopping
```

I think the important line is

```
10-11 11:58:34.346  1977  1977 E keystore: getAuthToken failed: -2
```

Could this be related to #1144?

**Comment by msfjarvis** [comment] 2020-10-11 10:10
Thanks for the logcat snippet.

> Could this be related to #1144?

Possibly, did you use the option to protect your generated key with your screen lock?

**Comment by blastrock** [comment] 2020-10-11 10:14
> Possibly, did you use the option to protect your generated key with your screen lock?

Yes, and I tried without the screen lock as jou suggested in #1144. I think the ssh connection did work. I got a lot of logs in logcat from `net.schmizz.sshj.connection.channel.direct.SessionChannel` dumping whole packets. But then it failed with

```
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:1)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:1)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at org.eclipse.jgit.api.RebaseCommand.call(RebaseCommand.java:25)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:69)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at com.zeapo.pwdstore.git.GitCommandExecutor$execute$2$result$1.invokeSuspend(GitCommandExecutor.kt:2)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:13)
```

Maybe that's an unrelated issue, my repository seems to be half-initialized as a consequence of these bugs. When I start the app, I get to the main screen with the list of password (which is empty) even though I never created a new repository or cloned one. So I believe this did confirm it's a keystore issue.

**Comment by msfjarvis** [comment] 2020-10-11 10:18
```
10-11 12:05:31.337 24120 24120 D PasswordFragment$initializePasswordList$1$$special$$inlined$apply$lambda: java.lang.NullPointerException: Attempt to read from field 'int org.eclipse.jgit.lib.AnyObjectId.w1' on a null object reference
```

Definitely means that the repository is in a bad state. Our detection of these is unfortunately best-effort and the issue keeps creeping up. Going into settings and using the delete repository option should allow you to start afresh without needing to reconfigure any of the server settings.

**Comment by blastrock** [comment] 2020-10-11 10:22
Yup, did that afterwards, it works, still with screen lock protection off :) 

We can close one of these two issues if you're convinced they're duplicate.

**Comment by msfjarvis** [comment] 2020-10-11 10:23
> Yup, did that afterwards, it works, still with screen lock protection off :)
> 
> We can close one of these two issues if you're convinced they're duplicate.

They are, I'm gonna close this and keep the other one open to track when Tink resolves the issue on their end.

**Closed as completed by msfjarvis** 2020-10-11 10:23 UTC
