### ISSUE TITLE
Configurable commit messages

### ISSUE THREAD

**Issue by bshkrv** [zeapo/Android-Password-Store#328] opened 2017-07-31 20:25 UTC
I would like commit [messages](https://github.com/zeapo/Android-Password-Store/blob/master/app/src/main/res/values/strings.xml#L24-L27) to be configurable, or at least to match ones from original password store. Are there any plans to make this happen?

**Comment by zeapo** [comment] 2017-08-01 21:28
Duplicate of #272

**Closed** 2017-08-13 10:40 UTC
