### ISSUE TITLE
[Question] Version on F-Droid lagging behind

### ISSUE THREAD

**Issue by Schueni1** [zeapo/Android-Password-Store#1057] opened 2020-08-26 14:28 UTC
The currently available version on F-Droid is still  1.9.2.
Is it complicated to release updates on F-Droid?

**Comment by fmeum** [comment] 2020-08-26 14:35
> Is it complicated to release updates on F-Droid?

Short answer: Yes, it is. ;-)
Long answer: We recently introduced variants in our builds and it took a long time for our F-Droid PR switching to the "free" variant to get merged. While this has happened now, the version of `fdroidserver` used by F-Droid to build our app currently doesn't support the Gradle plugin version we have updatet to in the meantime. Support is coming though: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7141#note_398470411

@msfjarvis If we wanted to speed this up, we could downgrade our Gradle wrapper to a version supported by F-Droid.

**Comment by msfjarvis** [comment] 2020-08-26 14:39
> > Is it complicated to release updates on F-Droid?
> 
> Short answer: Yes, it is. ;-)
> Long answer: We recently introduced variants in our builds and it took a long time for our F-Droid PR switching to the "free" variant to get merged. While this happened now, the version of `fdroidserver` used by F-Droid to build our app currently doesn't support the Gradle plugin version we are using. Support is coming though: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7141#note_398470411
> 
> @msfjarvis If we wanted to speed this up, we could downgrade our Gradle wrapper to a version supported by F-Droid.

I'm not willing to add workarounds to my project to fix F-Droid's incompetence. If their users can't get new versions of apps just because said apps are proactively updated then it's a failure of their system, not ours.

**Closed as completed** 2020-08-26 15:08 UTC

**Comment by fmeum** [comment] 2020-08-27 05:55
Update: I will add my own incompetence to the mix. I apparently misunderstood their build metadata format, which resulted in our version names being `v1.2.3-free-free` on F-Droid. Not sure whether this broke anything, but I'm hoping to get it fixed soon: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6998#note_402895928

Unfortunately, reproducible builds are no longer an option unless we rename our GitHub CI generated APKs and always add both a `v1.2.3` and a `v1.2.3-free` tag. @msfjarvis Would you be willing to do that to get us verified F-Droid/GitHub builds?

**Comment by msfjarvis** [comment] 2020-08-27 06:04
> Update: I will add my own incompetence to the mix. I apparently misunderstood their build metadata format, which resulted in our version names being `v1.2.3-free-free` on F-Droid. Not sure whether this broke anything, but I'm hoping to get it fixed soon: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6998#note_402895928
> 
> Unfortunately, reproducible builds are no longer an option unless we rename our GitHub CI generated APKs and always add both a `v1.2.3` and a `v1.2.3-free` tag. @msfjarvis Would you be willing to do that to get us verified F-Droid/GitHub builds?

That's going to be annoying w.r.t. GitHub releases... I'll see what can be done but It'd be much more preferable to just not need the separate tag. Would dropping the -free version suffix fix this?

**Comment by fmeum** [comment] 2020-08-27 06:07
> That's going to be annoying w.r.t. GitHub releases... I'll see what can be done but It'd be much more preferable to just not need the separate tag. Would dropping the -free version suffix fix this?

I think it would. If F-Droid releases were `v1.2.3` and Play Store releases were `v1.2.3-nonFree`, I think that F-Droid builds would simplify and allow using the Binaries directive.

**Comment by msfjarvis** [comment] 2020-08-27 06:14
> > That's going to be annoying w.r.t. GitHub releases... I'll see what can be done but It'd be much more preferable to just not need the separate tag. Would dropping the -free version suffix fix this?
> 
> I think it would. If F-Droid releases were `v1.2.3` and Play Store releases were `v1.2.3-nonFree`, I think that F-Droid builds would simplify and allow using the Binaries directive.

Can they both not be `v1.2.3`? I don't think I understand the need for an explicit suffix for either case.

**Comment by fmeum** [comment] 2020-08-27 06:15
> > > That's going to be annoying w.r.t. GitHub releases... I'll see what can be done but It'd be much more preferable to just not need the separate tag. Would dropping the -free version suffix fix this?
> > 
> > 
> > I think it would. If F-Droid releases were `v1.2.3` and Play Store releases were `v1.2.3-nonFree`, I think that F-Droid builds would simplify and allow using the Binaries directive.
> 
> Can they both not be `v1.2.3`? I don't think I understand the need for an explicit suffix for either case.

I guess they could. It seems to be rather common to have suffixes in this case, but I have also never understood why.
