### ISSUE TITLE
[BUG] App never opens

### ISSUE THREAD

**Issue by FloatingLizard** [zeapo/Android-Password-Store#3198] opened 2024-09-05 13:27 UTC
### Describe the bug

I have installed the app onto a Graphene on a Pixel 8 pro Android 14 device and once "Enable Biometric Authentication" is enabled the app launch but never displays anything on the main screen.  It is open, I have to disable the feature to actually see the content.
  Also is the version that 3 years old on F-droid is the latest? 
  
  Sorry I can reproduce the steps. 

### Steps to reproduce

once "Enable Biometric Authentication" is enabled the app launch but never displays anything on the main screen. 

### Expected behavior

To open the store

### Device information

- Device: Pixels 8 pro
- OS: Android 14
- App version: 1.13.5

**Comment by msfjarvis** [comment] 2024-09-05 14:09
Duplicate of #2802

**Closed as not planned by msfjarvis** 2024-09-05 14:09 UTC
Labels: C-bug, S-duplicate
