### ISSUE TITLE
Decrypt by authenticating with Fingerprint

### ISSUE THREAD

**Issue by metalmatze** [zeapo/Android-Password-Store#262] opened 2017-01-04 21:16 UTC
Hey, I really like the app. I use it on a daily basis and it's perfect. 👌 
I thought about using the Fingerprint reader to decrypt the store. 1password does the same thing within their app. It might be really convenient. 
I'm not sure about the security implications though... 

Thanks!

**Comment by zeapo** [comment] 2017-01-04 21:31
Hi,
Thank you for the kind comment.
The decryption using fingeprint, it's an OpenKeychain issue : https://github.com/open-keychain/open-keychain/issues/1642

They listed Keystore losing keys as an issue. We could suppose that we do not care about keystore losing our passphrase as the user should know the passphrase by heart, decrypt the passphrase and send it to Openkeychain...

**Comment by wiktor-k** [comment] 2017-01-20 19:34
I think the fingerprint could be used when opening the app as a way to hide the list of used sites and available credentials. But on the other hand when using the accessibility service one can infer which sites have passwords.

Personally I wouldn't use it for decryption as this can be already protected using smartcard PIN and touch.

**Comment by raindev** [comment] 2018-09-28 07:55
Looks like a duplicate of #156 (blocked on OpenKeychain).

**Closed** 2018-09-28 09:58 UTC
