### ISSUE TITLE
Internal exception occured. Message from jgit: HEAD is detached

### ISSUE THREAD

**Issue by xlogerais** [zeapo/Android-Password-Store#162] opened 2016-01-01 16:01 UTC
I get the following error when trying to pull from remote :
  Internal exeception occured
  Message from jgit:
  HEAD is detached

I don't know what happened, but it already worked.
I'm not using external repository option so I don't know if it is possible to "inspect" directory structure from command line to debug.
Is the "internal" directory structure accessible to the user ?

**Comment by xlogerais** [comment] 2016-01-02 18:21
I finally manage to access internal repo with root access.
The problem was caused by a conflict that prevented fast forward.
I think you can close this issue as it was not really a bug.
Maybe you can think about adding a feature to do a "git checkout --hard" to ease recover for such situations.

Regards,

Xavier Logerais.

PS: Thanks for your work ! I like your software.

**Comment by zeapo** [comment] 2016-01-02 20:25
We should not lock the user in a detached HEAD state.

**Comment by zeapo** [comment] 2016-01-02 20:26
Thanks @xlogerais for the issue. This should not happen as we do not give the user a direct access to the git repository, hence doing a reset or a rebase --abort is not possible directly.

**Comment by lekv** [comment] 2016-08-17 10:21
I just ran into this issue on a non-rooted device. Is there any way to recover from this, short of cleaning the app's data and re-configuring it?

**Comment by zeapo** [comment] 2016-08-17 10:23
@lekv are you using the PlayStore version or the F-Droid version?

**Comment by lekv** [comment] 2016-08-17 10:24
The one from the play store.

**Comment by zeapo** [comment] 2016-08-17 10:25
I will try to provide an apk with an option to do the `rebase --abort`. However, this will not fix the conflict.

**Comment by lekv** [comment] 2016-08-17 10:33
I was able to fix it by just re-checking out the repository, after re-visiting the git log on my desktop and making sure that I'll keep all but one current pw - so this is not urgent. Thanks for the help.

**Comment by zeapo** [comment] 2016-08-17 10:34
good then :)

**Comment by bignose-debian** [comment] 2016-09-04 00:52
This is difficult for the developers and impossible for the users to even diagnose properly, because the message should not be this uninformative. Issue #219 requests better treatment of exceptions like this one.

**Comment by slackline** [comment] 2017-03-29 06:02
I've encountered this and am struggling to work around it, any suggestions?

On the server I'm trying to synchronise from I've followed [these](https://stackoverflow.com/questions/5772192/how-can-i-reconcile-detached-head-with-master-origin) steps for resolving a detached head but Password-Store still reports a detached head when I try to synchronise or pull from it.

I'm using v1.2.0.57 from the F-Droid store.

**Comment by zeapo** [comment] 2017-03-29 07:18
The issue is that you're in a detached head in the app itself. This happens during the git rebase, maybe we could offer a way to detect it.

**Comment by ns-ctru** [comment] 2017-03-29 07:50
Ah ok, would a working solution be to delete the current existing store in the application (i.e. the directory I saved it to) and then re-sync as @lekv suggested further up?

**Comment by zeapo** [comment] 2017-03-29 07:57
yes, that would be a solution.

**Comment by slackline** [comment] 2017-03-29 19:55
Thanks, went with that option, any changes I made under Android will have been by mistake.

**Comment by jmeekhof** [comment] 2018-04-16 01:50
I know this thread is a bit stale, but could you allow someone to create a branch at the detached head? Then this could be pushed to a real computer where the conflict could be resolved.

**Comment by frostyfrog** [comment] 2018-07-01 19:20
Indeed, or maybe even dropping to the command line would suffice, if it's possible.

**Comment by anoadragon453** [comment] 2018-07-04 14:45
Yes, and I was just hit again by this today, so a working solution would be much appreciated.

**Comment by bjmgeek** [comment] 2018-07-07 11:12
​Seconded.  The only I was able to repair it was to delete the local repo
from my phone, and re-clone it.

**Comment by aut0** [comment] 2019-05-07 09:39
> I know this thread is a bit stale, but could you allow someone to create a branch at the detached head? Then this could be pushed to a real computer where the conflict could be resolved.

Moving changes in the app to a branch on conflict and pushing this to the git server would be a nice workaround. Would it be okay to open a bug bounty for this?

**Comment by zeapo** [comment] 2019-05-08 14:59
I opened a PR for this. 

This PR will allow you to push your local branch to another branch and stop the rebase. This way, you can clean the conflicts on your own machine.

**Closed** 2019-05-15 09:22 UTC
Labels: bug

**Comment by evanrmurphy** [comment] 2020-01-11 21:28
I'm having this same issue. I see #508 is a fix as @zeapo explains:

> This PR will allow you to push your local branch to another branch and stop the rebase. This way, you can clean the conflicts on your own machine.

Can you clarify how to actually do this? I have added a lot of passwords to my phone in this corrupted state so am worried about losing them if I just delete/re-clone.

Thank you for this fix and for Android Password Store!

**Comment by minami-o** [comment] 2020-02-03 23:12
> 
> 
> I'm having this same issue. I see #508 is a fix as @zeapo explains:
> Can you clarify how to actually do this? I have added a lot of passwords to my phone in this corrupted state so am worried about losing them if I just delete/re-clone.
If I'm not mistaken, you need to go to the Settings and, in the Git section, go to Edit configuration.
There, the Hackish tools section shows the current Commit hash and the button below, labelled "Abort rebase and push new branch", is self-explanatory.

**Comment by githlp** [comment] 2020-12-03 19:06
bump.
I had the same exception with the F-Droid v1.13.1

Internal exeception occured
HEAD is detached

No idea how i came to the detached head within the application, the other two (computer) clients had no problem syncing.
I was not able to solve it (even with Hard reset) and therefor finally removed the local repo so i could clone again from remote.

**Comment by msfjarvis** [comment] 2020-12-03 19:08
Please don't bump old issues, file new ones (properly following the template) if you come across regressions.
