### ISSUE TITLE
[FEATURE] implement templates

### ISSUE THREAD

**Issue by ecxod** [zeapo/Android-Password-Store#2378] opened 2023-02-14 11:21 UTC
### Is your feature request related to a problem? Please describe.

QTPass has a feature called templates, These templates cause all these keywords to turn into input windows and have "copy-the-content" button, so that you can copy the content of the field to the clipboard.

```
login
url
imap
imap-port
imap-auth
smtp
smtp-port
smtp-auth
datum
```

### Describe the solution you'd like

Could you implement that as well?

### Describe alternatives you've considered

- 

### Additional context

Elvis is alive

**Comment by msfjarvis** [comment] 2023-02-14 11:32
Duplicate of #1191, #1412, and #1478

**Closed as completed by msfjarvis** 2023-02-14 11:32 UTC
Labels: C-feature, S-duplicate
