### ISSUE TITLE
[BUG] Trust anchor for certification path not found

### ISSUE THREAD

**Issue by deividaspran** [zeapo/Android-Password-Store#2265] opened 2022-11-21 21:45 UTC
### Describe the bug

Hi. I'm trying to setup PasswordManager app with my own git server instance over HTTPS. I'm using a self signed certificate, which causes the following error:
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found
CA certificate is imported into Android settings and I can see the website is trusted when I open it up in the browser. 

### Steps to reproduce

1. Host a git server
2. Use self signed certificate for HTTPS
3. Import self signed CA to Android
4. Set the on prem git server on the Password Manager Android app settings
5. Pull / Push / Synchronize data

### Expected behavior

Git commands are successful

### Device information

- Device: Samsung Fold 3
- OS: Anndroid 12
- App version 1.13.5

**Comment by msfjarvis** [comment] 2022-11-22 04:34
Duplicate of https://github.com/android-password-store/Android-Password-Store/issues/1318

**Closed as not planned by msfjarvis** 2022-11-22 04:34 UTC
Labels: C-bug, S-invalid

**Comment by Raekye** [comment] 2022-11-25 05:25
#1318 says:

> With https://github.com/android-password-store/Android-Password-Store/commit/f7766bc67aa3aa808bd40fac13dcdae5126017ed it should be possible to connect to servers that are behind self-signed certs but I'm not confident about the security implications of this change.

Which sounds like it should be supported. But clicking on that commit, GitHub says:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Then I noticed this issue is closed as "not planned". Is it because of the "security implications" of the change?

**Comment by msfjarvis** [comment] 2022-11-25 05:27
> #1318 says:
> 
> > With [f7766bc](https://github.com/android-password-store/Android-Password-Store/commit/f7766bc67aa3aa808bd40fac13dcdae5126017ed) it should be possible to connect to servers that are behind self-signed certs but I'm not confident about the security implications of this change.
> 
> Which sounds like it should be supported. But clicking on that commit, GitHub says:
> 
> > This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
> 
> Then I noticed this issue is closed as "not planned". Is it because of the "security implications" of the change?

Yes, the commit was never merged because I couldn't get a clear answer and did not want to make an uninformed decision on changing the existing default.

**Comment by Raekye** [comment] 2022-11-25 06:49
I'm no security expert so I could be missing something, but I am trying to use my own signed CA so I have an interest in this feature; here's my pitch.

1. At least for me, one of the reasons to use [pass](https://www.passwordstore.org/) is that I don't need to trust any service; the tools are open source, and as such, there's no obfuscation - only encryption, and auditable. On one hand, this means I should be safe uploading my git repo to, for example, GitHub, which has valid certificates. On the other hand, if I'm using something like `pass`, I'm already trying to reduce my dependence on 3rd party services. It seems natural to me to self-host such a git repo - except when self-hosting, it's unlikely to have a certificate signed by a 3rd party CA. Basically, it seems to me "in the spirit" of `pass` to be able to self-host (in which case, the user is probably self-signing and importing their certificate).
2. Of course, the actual security is important, but I don't see how this fundamentally changes anything. That commit would allow users to trust custom certificates - which may or may not be intended (maybe they got tricked into installing a malicious certificate). Then, they might pull/push from a remote they didn't intend to. Obviously sending any data to an attacker is unideal, but in terms of security, is gpg's encryption not the only thing that matters? Assume that an attacker can crack our gpg keys. Were things really more safe in a GitHub repository (or with any 3rd party who had a valid SSL certificate)?
